### ISSUE TITLE
test_xpickle failure, something about builtins.sentinel

### ISSUE THREAD

**Issue by smontanaro** [python/cpython#149650]
# Bug report

### Bug description:

`test_xpickle` is failing on MacOS for me (main branch). It seems there's a new `sentinel` name in `builtins`. I see a bunch tracebacks like this:

```
ERROR: test_builtin_types (test.test_xpickle.CPicklePython315Compat.test_builtin_types) (name='sentinel', proto=5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/skip/src/python/cpython/Lib/test/pickletester.py", line 3300, in test_builtin_types
    s = self.dumps(t, proto)
  File "/Users/skip/src/python/cpython/Lib/test/test_xpickle.py", line 190, in dumps
    return self.send_to_worker(python, data)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/skip/src/python/cpython/Lib/test/test_xpickle.py", line 172, in send_to_worker
    raise exception
AttributeError: module 'builtins' has no attribute 'sentinel'
```

I suspect it's expecting – but not finding – `sentinel` in the builtins of older versions. The test finds versions of the interpreter on my machine from 3.7 onwards. FWIW, it passes on my Ubuntu laptop (many fewer versions of the interpreter there, however). Seems odd that it would be MacOS-specific though.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

**Comment by smontanaro** [comment]
I just verified that `test_xpickle` works on the 3.15 branch. (`main` reports that it is 3.16.0a0.)

**Comment by JelleZijlstra** [comment]
I suspect this might be because you have a local 3.15 installation that predates the addition of `builtins.sentinel`?

**Comment by StanFromIreland** [comment]
The test passes on the Buildbot: https://buildbot.python.org/#/workers/123

**Comment by smontanaro** [comment]
> I suspect this might be because you have a local 3.15 installation that predates the addition of `builtins.sentinel`?

Thanks, indeed I do (now did). The date of that installation was March 1. I just wiped it all out and the test now passes.
