### ISSUE TITLE
`test_monitoring` has duplicated tests

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#106193]
Based on https://github.com/python/core-workflow/issues/505 by @hugovk 

```
Lib/test/test_monitoring.py:973:5: F811 redefinition of unused 'test_line_then_instruction' from line 950
Lib/test/test_monitoring.py:978:5: F811 redefinition of unused 'test_instruction_then_line' from line 955
```

Before rename: `Ran 49 tests in 0.014s`
After rename:

```
======================================================================
ERROR: test_instruction_then_line (test.test_monitoring.TestInstallIncrementallly.test_instruction_then_line)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_monitoring.py", line 956, in test_instruction_then_line
    recorders = [ InstructionRecorder, LineRecorderLowNoise ]
                                       ^^^^^^^^^^^^^^^^^^^^
NameError: name 'LineRecorderLowNoise' is not defined

======================================================================
ERROR: test_line_then_instruction (test.test_monitoring.TestInstallIncrementallly.test_line_then_instruction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_monitoring.py", line 953, in test_line_then_instruction
    recorders = recorders, must_include = self.EXPECTED_LI)
                                          ^^^^^^^^^^^^^^^^
AttributeError: 'TestInstallIncrementallly' object has no attribute 'EXPECTED_LI'

----------------------------------------------------------------------
Ran 51 tests in 0.045s

FAILED (errors=2)
test test_monitoring failed
test_monitoring failed (2 errors)

== Tests result: FAILURE ==

1 test failed:
    test_monitoring

Total duration: 94 ms
Tests result: FAILURE
```

Based on the missing runtime parts in these tests, we can just remove the first two ones, I guess.

Both of these tests were introduced in https://github.com/python/cpython/commit/411b1692811b2ecac59cb0df0f920861c7cf179a by @markshannon 

### Linked PRs
* gh-109139
* gh-110897

**Comment by sobolevn** [comment]
No, they cannot be just deleted, because they test different things.

**Comment by sobolevn** [comment]
Introduced in https://github.com/python/cpython/pull/103083/commits/b32a075094f175ad30fef0939ac48016ec34f3fd#diff-15fb0cb29709c04c449bacd69e4ab2208372424d8390c26258eb83b2363c3cf1 

Looks like it never had parts that are missing right now.

**Comment by hugovk** [comment]
Please see PR https://github.com/python/cpython/pull/109139.
