### ISSUE TITLE
Regression in multiprocessing on Windows under coverage and ctypes

### ISSUE THREAD

**Issue by jaraco** [python/cpython#105914]
In https://github.com/jaraco/keyring/issues/634#issuecomment-1597346621, I finally managed to replicate an issue encountered in keyring. Starting sometime between 3.12a7 and 3.12b1, the keyring test suite started failing on Windows tests running under multiprocessing when pytest-cov is involved.

I'm not yet convinced that the issue doesn't lie with pytest or pytest-cov or ctypes, but given that the issue started with a beta release of Python, it's the most likely culprit.

I'll try to continue to distill the issue, but I wanted to register this report early, as it may be a release blocker.

**Comment by jaraco** [comment]
I've confirmed that the issue occurs without `pytest-cov` but using native coverage:

```
pip-run -- -m coverage run -m pytest mod.py
```

Using rev 2 of [mod.py](https://gist.github.com/jaraco/7ca878b74b80a88a89936957825baa49).

(if you don't have pip-run, you may instead `pip install` the `__requires__` and then `py -m coverage run -m pytest mod.py`).

**Comment by jaraco** [comment]
In [rev 3 of mod.py](https://gist.github.com/jaraco/7ca878b74b80a88a89936957825baa49/b1eda5087391a45f40e97749c6d8153199bde266), I've successfully replicated the failure with only `coverage` and `pywin32-ctypes` (excluding pytest).

**Comment by jaraco** [comment]
Curiously, this script, where I've inlined the ctypes functionality from pywin32-ctypes, doesn't exhibit the failure:

<details>

```python
# run with:
# pip-run -- -m coverage run mod.py
__requires__ = ['coverage']

import ctypes
from ctypes import POINTER, c_void_p, c_wchar_p
from ctypes.wintypes import DWORD, FILETIME, BYTE, BOOL, LPCWSTR
import multiprocessing

LPBYTE = POINTER(BYTE)


class CREDENTIAL(ctypes.Structure):
    _fields_ = [
        ("Flags", DWORD),
        ("Type", DWORD),
        ("TargetName", c_wchar_p),
        ("Comment", c_wchar_p),
        ("LastWritten", FILETIME),
        ("CredentialBlobSize", DWORD),
        ("CredentialBlob", LPBYTE),
        ("Persist", DWORD),
        ("_DO_NOT_USE_AttributeCount", DWORD),
        ("__DO_NOT_USE_Attribute", c_void_p),
        ("TargetAlias", c_wchar_p),
        ("UserName", c_wchar_p)]


PCREDENTIAL = POINTER(CREDENTIAL)
PPCREDENTIAL = POINTER(PCREDENTIAL)


_CredRead = ctypes.WinDLL('advapi32').CredReadW
_CredRead.restype = BOOL
_CredRead.argtypes = [LPCWSTR, DWORD, DWORD, PPCREDENTIAL]


def run():
    pcreds = PCREDENTIAL()
    res = _CredRead('test', 1, 0, ctypes.byref(pcreds))
    assert res == 0
    code = ctypes.GetLastError()
    if code != 1168:
        raise RuntimeError(f"Unexpected code {code}")

    return pcreds


def run_child():
    run()
    proc1 = multiprocessing.Process(target=run)
    proc1.start()
    proc1.join()
    assert proc1.exitcode == 0


__name__ == '__main__' and run_child()
```

</details>

Maybe [pywin32-ctypes' caching of dlls](https://github.com/enthought/pywin32-ctypes/blob/be42cbb26950d8e4cc29ffd3168c3b44478ac18d/win32ctypes/core/ctypes/_util.py#L70-L78) is relevant?

**Comment by jaraco** [comment]
> Maybe [pywin32-ctypes' caching of dlls](https://github.com/enthought/pywin32-ctypes/blob/be42cbb26950d8e4cc29ffd3168c3b44478ac18d/win32ctypes/core/ctypes/_util.py#L70-L78) is relevant?

Seems not, because I added in that caching and it still doesn't fail.

<details>

```python
...
class Libraries(object):

    def __getattr__(self, name):
        library = ctypes.WinDLL(name)
        self.__dict__[name] = library
        return library


dlls = Libraries()


_CredRead = dlls.advapi32.CredReadW
...
```

</details>

**Comment by jaraco** [comment]
I'm punting on this for now. I think the next step in the investigation might be to bisect the CPython source and figure out when the failure starts or maybe just scan through the changes between a7 and b1 and see if anything pops out as possibly relevant.

**Comment by eryksun** [comment]
With revision 3 of "mod.py", running `pip-run -- -m coverage run mod.py` raises no error on Windows 11 with Python 3.12b2. I added a print statement in `run()` to confirm that it handles an exception for `ERROR_NOT_FOUND` (1168) when `CredRead()` is called in both the parent and child process.

**Comment by jaraco** [comment]
That's strange, because it's still failing for me:

<details>

```
PS C:\Users\jaraco\draft> pip-run -- -V
Python 3.12.0b2
PS C:\Users\jaraco\draft> cat mod.py
# run with:
# pip-run -- -m coverage run mod.py
__requires__ = ['pywin32-ctypes', 'coverage']

import multiprocessing

from win32ctypes.pywin32 import win32cred
from win32ctypes.pywin32 import pywintypes


def run():
    try:
        return win32cred.CredRead(Type=win32cred.CRED_TYPE_GENERIC, TargetName='test')
    except pywintypes.error as e:
        if e.winerror == 1168 and e.funcname == 'CredRead':  # not found
            return None
        raise


def run_child():
    assert run() is None
    proc1 = multiprocessing.Process(target=run)
    proc1.start()
    proc1.join()
    assert proc1.exitcode == 0


def test_run_child():
    run_child()


__name__ == '__main__' and run_child()

PS C:\Users\jaraco\draft> pip-run -v -- -m coverage run mod.py
Collecting coverage
  Using cached coverage-7.2.7-cp312-cp312-win_arm64.whl
Installing collected packages: coverage
Successfully installed coverage-7.2.7
Traceback (most recent call last):
  File "C:\Users\jaraco\AppData\Roaming\Python\Python312-arm64\site-packages\win32ctypes\pywin32\pywintypes.py", line 33, in pywin32error
    yield
  File "C:\Users\jaraco\AppData\Roaming\Python\Python312-arm64\site-packages\win32ctypes\pywin32\win32cred.py", line 68, in CredRead
    _authentication._CredRead(
  File "C:\Users\jaraco\AppData\Roaming\Python\Python312-arm64\site-packages\win32ctypes\core\ctypes\_util.py", line 61, in check_false
    raise make_error(function, function_name)
OSError: [WinError 2] The system cannot find the file specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jaraco\draft\mod.py", line 32, in <module>
    __name__ == '__main__' and run_child()
                               ^^^^^^^^^^^
  File "C:\Users\jaraco\draft\mod.py", line 21, in run_child
    assert run() is None
           ^^^^^
  File "C:\Users\jaraco\draft\mod.py", line 13, in run
    return win32cred.CredRead(Type=win32cred.CRED_TYPE_GENERIC, TargetName='test')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaraco\AppData\Roaming\Python\Python312-arm64\site-packages\win32ctypes\pywin32\win32cred.py", line 61, in CredRead
    with _pywin32error():
  File "C:\Program Files\Python 3.12\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(value)
  File "C:\Users\jaraco\AppData\Roaming\Python\Python312-arm64\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (2, 'CredRead', 'The system cannot find the file specified.')
```

</details>


I am using Windows 11 Pro for ARM (Build 23440.ni_prerelease.230414-1348), but I don't think that's relevant as the tests in Github Actions are failing too and I'm all but certain that's Windows for x64.

Thinking there might be something unusual in my environment or something relating to pip-run, I removed all dependencies and installed `pywin32-ctypes==0.2.1` and `coverage==7.2.7` and ran the script with `py -m coverage run mod.py` and I still get the failure.

**Comment by jaraco** [comment]
I wonder if maybe there's a race condition. In both GHA and on my machine (UTM virtual machine), I've observed slowness due to resource contention, so perhaps that's relevant to replicating the issue. Oh! I know - I'll replicate it with a Github action.

**Comment by jaraco** [comment]
I created the repro in https://github.com/python/gh-105914/, but the CI passes. I noticed that 3.12b3 was released only a few days ago and that's what CI is using now. I'll try that.

**Comment by jaraco** [comment]
In https://github.com/jaraco/keyring/actions/runs/5351757799/jobs/9705956051, I can see that the tests are xpassing (no longer failing).

But even after upgrading Python to 3.12b3 on my Windows machine, the repro still fails. I'm going to try a clean install of Python.

**Comment by eryksun** [comment]
That's the wrong Windows error code. WinAPI [`CredReadW()`](https://learn.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credreadw) should fail with `ERROR_NOT_FOUND` (1168) in this case, not `ERROR_FILE_NOT_FOUND` (2).

The use of `ctypes.GetLastError()` in "win32ctypes/core/ctypes/_util.py" is dubious. In general, WinAPI function prototypes should use `use_last_error=True`. It can be configured on `ctypes.WinDLL` instances or on individual `ctypes.WINFUNCTYPE()` prototypes. This setting causes the thread's last error value to be saved to a thread-local value in C, immediately before and after the FFI call. Code can get and set the thread-local value via `ctypes.get_last_error()` and `ctypes.set_last_error()`, and raise a formatted `OSError` exception via `raise ctypes.WinError(ctypes.get_last_error())`.

**Comment by jaraco** [comment]
I managed to work around the issue by running `pip cache purge`. That caused coverage to be re-built from sdist instead of re-using the cached wheel that was previously built on b1 or b2 (and also caused pywin32_ctypes to be downloaded again).

**Comment by jaraco** [comment]
I rebuilt the (still failing) keyring test environment on that machine and it no longer fails either. Something about those cached artifacts (coverage) was likely implicated. Before I rebuilt the tox environment, I zipped it up ([keyring.zip](https://github.com/python/cpython/files/11843912/keyring.zip)) so we would have a way to recreate the failure if needed. I wish I'd somewhere saved the wheel before I purged the pip cache, but alas, I did not, so all we have are the installed artifacts.

**Comment by jaraco** [comment]
> That's the wrong Windows error code. WinAPI [`CredReadW()`](https://learn.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credreadw) should fail with `ERROR_NOT_FOUND` (1168) in this case, not `ERROR_FILE_NOT_FOUND` (2). I always see `ERROR_NOT_FOUND` in Python 3.12b2.

That's really interesting that you didn't encounter the issue on 3.12b2, but [keyring did](https://github.com/jaraco/keyring/actions/runs/5293285392/jobs/9581225875). To complicate matters, [pywin32-ctypes had a release on Monday](https://github.com/enthought/pywin32-ctypes/releases/tag/v0.2.1).

> The use of `ctypes.GetLastError()` in "win32ctypes/core/ctypes/_util.py" is dubious. In general, WinAPI function prototypes should use `use_last_error=True`. It can be configured on `ctypes.WinDLL` instances or on individual `ctypes.WINFUNCTYPE()` prototypes. This setting causes the thread's last error value to be saved to a thread-local value in C, immediately after the FFI call, before any other Python runtime or Python code can be called. Code can get and set the thread-local value via `ctypes.get_last_error()` and `ctypes.set_last_error()`, and raise a formatted `OSError` exception via `raise ctypes.WinError(ctypes.get_last_error())`.

That's good insight. I wonder if something about this use of GetLastError and the interaction with coverage was somehow causing errors from coverage to leak into the pywin32 call.

I'll file your suggestion with the project.

Unfortunately, the keyring zip I saved somehow didn't include the .tox directory (though it did grab .git). I used Windows explorer to zip up the whole directory, so I'm not sure why it didn't include the .tox directory.

**Comment by jaraco** [comment]
I'm now thinking that pywin32-ctypes 0.2.0 may have had other issues that could have affected the behavior:

```
 draft @ py -3.11 -m pip-run pywin32-ctypes==0.2.0 -- -c "from win32ctypes.pywin32 import win32cred"
 draft @ py -3.12 -m pip-run pywin32-ctypes==0.2.0 -- -c "from win32ctypes.pywin32 import win32cred"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\jaraco\AppData\Local\Temp\pip-run-cijyyafy\win32ctypes\pywin32\__init__.py", line 11, in <module>
    from win32ctypes.pywin32 import win32api
  File "C:\Users\jaraco\AppData\Local\Temp\pip-run-cijyyafy\win32ctypes\pywin32\win32api.py", line 12, in <module>
    from win32ctypes.core import (
ImportError: cannot import name '_common' from 'win32ctypes.core' (C:\Users\jaraco\AppData\Local\Temp\pip-run-cijyyafy\win32ctypes\core\__init__.py)  
```

I see 0.2.1 added [support for .find_spec](https://github.com/enthought/pywin32-ctypes/pull/120), so how on earth did 0.2.0 ever work with 3.12b1/b2? Aha! It never did. The tests were skipped and failing (https://github.com/jaraco/keyring/actions/runs/5293285392/jobs/9581225875#step:5:75). I wondered why those errors went away mysteriously when I started testing locally. It was because pywin32-ctypes had a release around the same time.

At this point, I'm no longer able to replicate the failure and all failure modes seem to have been addressed by updates to Python and pywin32-ctypes and purging caches.
