### ISSUE TITLE
[3.15.0a8] Build error if specialization is disabled

### ISSUE THREAD

**Issue by cdce8p** [python/cpython#148825]
# Bug report

### Bug description:

Set `ENABLE_SPECIFICATION = 0` and run `make`.
https://github.com/python/cpython/blob/d206d42834b2a34aee11b048357131371cf6947d/Include/internal/pycore_code.h#L301

```
Python/specialize.c:119:31: error: use of undeclared identifier 'opcode'
  119 |         i += _PyOpcode_Caches[opcode];
      |                               ^
1 error generated.
make: *** [Python/specialize.o] Error 1
```

The bug was introduced in https://github.com/python/cpython/commit/879c85f6e4ca8424ff6b4fddfbc946889572bf13, released with 3.15.0a8.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-148826
