### ISSUE TITLE
Python 3.12+ breaks backwards compatibility for logging QueueHandler with queue.SimpleQueue

### ISSUE THREAD

**Issue by spacemanspiff2007** [python/cpython#124653]
# Bug report

### Bug description:

I think this is related to #119819

```python
import logging.config
from queue import SimpleQueue

q = SimpleQueue()

config = {
    'version': 1,
    'handlers': {
        'sink': {
            'class': 'logging.handlers.QueueHandler',
            'queue': q,
        },
    },
    'root': {
        'handlers': ['sink'],
    },
}
logging.config.dictConfig(config)
```
```
ValueError: Unable to configure handler 'sink'
```

SimpleQueue does not implement the full Queue interfaces thus both ````isinstance(obj, queue.Queue)```` and the queue interface check fails.
Since this has been working on 3.8 - <3.12 I think the queue interface check is checking for methods that are not used at all and should be adjusted accordingly.

https://github.com/python/cpython/blob/25189188bfcb48be653eb9fb3aee892f2b9539b9/Lib/logging/config.py#L500-L525

Tested with 3.12.6

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-124897
* gh-125059
* gh-125060

**Comment by YvesDup** [comment]
Except if I miss something,  `SimpleQueue` has never had a `put_nowait` method, the one used in the `QueueHandler` and `QueueListener` classes ([Just see here](https://github.com/python/cpython/blob/3.13/Lib/logging/handlers.py#L1451)) . So using this class in the logging `QueueHandler` always failed.

**Comment by spacemanspiff2007** [comment]
As I've written this has been working on 3.8 - 3.11. I'm not sure exactly when it broke.
Since it works, `SimpleQueue` actually must implement [put_nowait](https://docs.python.org/3.13/library/queue.html#queue.SimpleQueue.put_nowait). 

I skimmed over the file and it seems the only required interface methods are `put_nowait` and `get`.
The interface check should reflect that.
Additionally `get` has to raise `queue.Empty` if the queue is empty but there is no way to check that ...

**Comment by YvesDup** [comment]
My apologies for my mistaken: I was thinking you talked about `multiprocessing.SimpleQueue` not about `queue.SimpleQueue`. So first of all, I suggess to modify title issue (prefixing  `SimpleQueue`with the `queue` module).

And then, I agree with you the `queue_interface` list of the `_is_queue_like_object` method is too restrictive. At least `join` and `task_done` methods must be removed. `full` and `empty`methods (or exceptions) have to exam too.

Perhars it will be nice to ask for a python core dev advice.

**Comment by YvesDup** [comment]
@picnixz as [GH-122154](https://github.com/python/cpython/pull/122154) author, and introducing `is_queue_like_object` in file `logging/config.py`,  could you take a look to this issue please ?

**Comment by YvesDup** [comment]
> So I think we should only care about two methods that are those given in SimpleQueue.

What do you think about adding `queue.simpleQueue` at L502, as below:
```
if isinstance(obj, (queue.Queue, queue.SimpleQueue)): 
         return True 
```

**Comment by picnixz** [comment]
It's correct (and that's what I also did), but since we really don't know whether people could use objects or not I just relaxed the interface (and I think it's fine like this).

**Comment by YvesDup** [comment]
@spacemanspiff2007 good catch !!

**Comment by picnixz** [comment]
I should be the one thanking you since this was my code :') sorry for the inconvenience!
