### ISSUE TITLE
Regression: importlib.metadata.PathDistribution.requires raises AttributeError, name/version raises TypeError

### ISSUE THREAD

**Issue by hroncok** [python/cpython#143387]
# Bug report

## Python 3.14.2

```pycon
>>> from importlib import metadata
>>> d = metadata.PathDistribution.at('/tmp')
>>> d.requires
>>> d.requires is None
True
```

## Python 3.15.0a3

```pycon
>>> from importlib import metadata
>>> d = metadata.PathDistribution.at('/tmp')
>>> d.requires
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    d.requires
  File "/usr/lib64/python3.15/importlib/metadata/__init__.py", line 660, in requires
    reqs = self._read_dist_info_reqs() or self._read_egg_info_reqs()
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib64/python3.15/importlib/metadata/__init__.py", line 664, in _read_dist_info_reqs
    return self.metadata.get_all('Requires-Dist')
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_all'
```

I believe this is a regression from 9b38c6698a3d6e7b37279dd9ae0d4d6430f9c612 where the `metadata` property changed the type from `_meta.PackageMetadata` to `_meta.PackageMetadata | None`  but other properties (here the `requires` property) do not account for it being `None`.

This was discovered as a failure of tests of rpmlint in Fedora's continuous testing of Python pre-releases: https://bugzilla.redhat.com/show_bug.cgi?id=2424585

### CPython versions tested on:

3.15

### Operating systems tested on:

Linux

### Linked PRs
* gh-146234

**Comment by hroncok** [comment]
Upstream commit is https://github.com/python/importlib_metadata/commit/57f31d77e18fef11dfadfd44775f253971c36920 from https://github.com/python/importlib_metadata/pull/519 -- unfortunately, neither the commit nor the PR provide rationale for this change.

**Comment by tomasr8** [comment]
cc @jaraco

**Comment by hugovk** [comment]
I talked with @jaraco and he'll take a look at this towards the end of the week.

**Comment by jaraco** [comment]
This change was an intentional one, and I apologize for it not being clearly traceable to the rationale.

I only had to go one level deeper from python/importlib_metadata#519 to https://github.com/python/importlib_metadata/issues/493 to see the rationale.

> Instead, I would expect `dist.metadata` to be `None` when no metadata file is present, and to return an empty `PackageMetadata` object when a metadata file is present but empty.

And one layer deeper https://github.com/python/importlib_metadata/issues/489#issuecomment-2195177710 describes where the Python 3.14 behavior missed expectations (and conflated the absence of metadata with a degenerate, empty metadata).



> I am not quite sure this is a proper fix. Considering `self.metadata` being None is a breaking change, I think the best way forward is to revert it.

I was assuming, perhaps incorrectly, that there would be little if any reliance on reading `Distribution.metadata` from invalid sources, so this change while technically incompatible was also refining the behavior around previously-unsupported edge cases, adding fidelity where the previous behavior was undefined and incidental. As mentioned in the above comments, I'd have expected `email.message_from_string(None)` to have raised an Exception and not produced a degenerate result, so it was an accident (and a bug) that this edge case didn't fail.

Based on those assumptions, I was treating this change as a (technically incompatible, but acceptable) bugfix.

> Given a set of arguments, the return value, side effects, and raised exceptions of a function. This does not preclude changes from reasonable bug fixes.

Seeing the examples above, I'm now more concerned about the uses resulting from Hyrum's law.

I did release this behavior early in order to gather feedback, and based on this feedback, it does deserve some reconsideration. I don't want to simply revert the behavior, as I'd like to understand what is the proper design moving forward and whether or not that change deserves a deprecation period.

Regarding the `.metadata` property, I do feel as if the `None` value better reflects the reality of the situation, and my instinct was that downstream consumers not handling `None` should crash (including cases that hit internal use as reported above). Or maybe better would be to throw an exception (`MetadataNotFound`) and avoid the `None` return type altogether. I do feel it's important to help consumers distinguish between a metadata folder with a missing METADATA file (but potentially containing other metadata) and one with an empty METADATA file.

Let's not revert this quite yet.

@hugovk Based on my explanation above and the fact that this use case was only viable due to an accident in the underlying APIs, do you want to retroactively support the behavior and demand a deprecation period for the change?

To everyone else, what should be the desired behavior when resolving "metadata" (i.e. the fields) for a folder that lacks the METADATA file? Exception, None, or something else (maybe a DegeneratePackageMetadata object that's distinct from actual PackageMetadata)? My instinct now is it should raise an Exception (and keep the API pure).

**Comment by hroncok** [comment]
> Unfortunately, I have no data for this. I know about [rpmlint](https://bugzilla.redhat.com/show_bug.cgi?id=2424585) and [pipdeptree](https://github.com/tox-dev/pipdeptree/issues/530) only.

After the recent change has landed, we see one more package that fails tests with `importlib.metadata.MetadataNotFound: No package metadata was found.` -- **pip**.

Note that those might already be fixed upstream, we have not dug into that yet.

```
________ test_trailing_slash_directory_metadata[/path/to/foo.egg-info/] ________
[gw0] linux -- Python 3.15.0 /usr/bin/python3

path = '/path/to/foo.egg-info/'

    @pytest.mark.parametrize(
        "path",
        [
            "/path/to/foo.egg-info".replace("/", os.path.sep),
            # Tests issue fixed by https://github.com/pypa/pip/pull/2530
            "/path/to/foo.egg-info/".replace("/", os.path.sep),
        ],
    )
    def test_trailing_slash_directory_metadata(path: str) -> None:
        dist = get_directory_distribution(path)
>       assert dist.raw_name == dist.canonical_name == "foo"
               ^^^^^^^^^^^^^

tests/unit/metadata/test_metadata.py:148: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../BUILDROOT/usr/lib/python3.15/site-packages/pip/_internal/metadata/base.py:416: in raw_name
    return self.metadata.get("Name", self.canonical_name)
           ^^^^^^^^^^^^^
/usr/lib64/python3.15/functools.py:1169: in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
../BUILDROOT/usr/lib/python3.15/site-packages/pip/_internal/metadata/base.py:391: in metadata
    metadata = self._metadata_impl()
               ^^^^^^^^^^^^^^^^^^^^^
../BUILDROOT/usr/lib/python3.15/site-packages/pip/_internal/metadata/importlib/_dists.py:210: in _metadata_impl
    return cast(email.message.Message, self._dist.metadata)
                                       ^^^^^^^^^^^^^^^^^^^
/usr/lib64/python3.15/importlib/metadata/__init__.py:543: in metadata
    return self._assemble_message(self._ensure_metadata_present(text))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <importlib.metadata.PathDistribution object at 0x7f7c90b2f480>
text = None

    def _ensure_metadata_present(self, text: str | None) -> str:
        if text is not None:
            return text
    
>       raise MetadataNotFound('No package metadata was found.')
E       importlib.metadata.MetadataNotFound: No package metadata was found.
```

EDIT: Already fixed upstream in https://github.com/pypa/pip/issues/13901 https://github.com/pypa/pip/pull/13902

**Comment by befeleme** [comment]
Also **poetry** has been affected.

**Comment by jaraco** [comment]
@befeleme Please provide more details (an issue reference or details about how they're affected and what the impact is). Most important - is this a case that's easily adapted to support both the old and new behaviors? Are there cases where poetry users won't be able to adopt the fix on newer Pythons?

**Comment by jaraco** [comment]
I too have stumbled onto a case that relied on the previous behavior (https://github.com/coherent-oss/coherent.build/blob/57c90b78a1d3959a986f70463a1893d53a994c5f/backend.py#L45). In that case, it's specifically relying on the `None` return value for invalid metadata to detect the lack of metadata. It's probably easy enough to bridge the gap (and specifically drop the "`None` also means present but empty" support in the future.

**Comment by jaraco** [comment]
Three cases has me concerned and I'm leaning toward adding a compatibility shim and deprecation period now.

**Comment by hroncok** [comment]
The poetry test failure is not yet triaged in Fedora. It might have been fixed upstream already, as it was for pip.

```
________________ test_load_successful_with_invalid_distribution ________________
[gw1] linux -- Python 3.15.0 /usr/bin/python3

caplog = <_pytest.logging.LogCaptureFixture object at 0x7ff6dd4206e0>
mocker = <pytest_mock.plugin.MockerFixture object at 0x7ff6bbe5e1a0>
env = _MockEnv("/tmp/pytest-of-mockbuild/pytest-0/popen-gw1/session-working-directory0/installed")
tmp_path = PosixPath('/tmp/pytest-of-mockbuild/pytest-0/popen-gw1/test_load_successful_with_inva0')
installed_results = [<importlib.metadata.PathDistribution object at 0x7ff6bb9eb700>, <importlib.metadata.PathDistribution object at 0x7ff6...tadata.PathDistribution object at 0x7ff6bb9e9090>, <importlib.metadata.PathDistribution object at 0x7ff6bb9e85f0>, ...]

    def test_load_successful_with_invalid_distribution(
        caplog: LogCaptureFixture,
        mocker: MockerFixture,
        env: MockEnv,
        tmp_path: Path,
        installed_results: list[metadata.PathDistribution],
    ) -> None:
        invalid_dist_info = tmp_path / "site-packages" / "invalid-0.1.0.dist-info"
        invalid_dist_info.mkdir(parents=True)
        mocker.patch(
            "importlib.metadata.Distribution.discover",
            return_value=[*installed_results, metadata.PathDistribution(invalid_dist_info)],
        )
>       repository_with_invalid_distribution = InstalledRepository.load(env)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/builddir/build/BUILD/poetry-2.3.4-build/poetry-2.3.4/tests/repositories/test_installed_repository.py:198: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/builddir/build/BUILD/poetry-2.3.4-build/BUILDROOT/usr/lib/python3.15/site-packages/poetry/repositories/installed_repository.py:273: in load
    dist_metadata = distribution.metadata  # type: ignore[attr-defined]
                    ^^^^^^^^^^^^^^^^^^^^^
/usr/lib64/python3.15/importlib/metadata/__init__.py:543: in metadata
    return self._assemble_message(self._ensure_metadata_present(text))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <importlib.metadata.PathDistribution object at 0x7ff6ba277f70>
text = None

    def _ensure_metadata_present(self, text: str | None) -> str:
        if text is not None:
            return text
    
>       raise MetadataNotFound('No package metadata was found.')
E       importlib.metadata.MetadataNotFound: No package metadata was found.

/usr/lib64/python3.15/importlib/metadata/__init__.py:556: MetadataNotFound
```

**Comment by jaraco** [comment]
Confirmed it was fixed upstream (https://github.com/python-poetry/poetry/commit/f47e6b2f73e6ea6e1f81fa8963ec0fde30815345).

**Comment by jaraco** [comment]
Based on how uncommon these regressions are and how easy it's been for each project to adapt, I'm inclined now to declare this issue as complete. @hroncok Are you satisfied? @hugovk Do you concur?

I do now think this change deserves a "changed in" note in the docs. I'll add that.

**Comment by hroncok** [comment]
I stand by my opinion that the public API and behavior of the standard library should follow the declared backward compatibility guarantees.

That said, this is not the hill I am willing to die on. If you insist on the change, please at least document it in What's new in Python 3.15.

**Comment by jaraco** [comment]
Thanks Miro.

Hugo, let me know if I should add the note in What's New, or if that's something someone else will do (in the past, that's generally been handled by someone other than me).

**Comment by hugovk** [comment]
@jaraco Please add it to What's New.

Nowadays we prefer contributors to update it directly (when needed), and then we might do some editing later.

**Comment by hroncok** [comment]
FTR another one: https://github.com/Pylons/plaster/pull/38
