### ISSUE TITLE
3.11 no longer builds with a configured empty prefix

### ISSUE THREAD

**Issue by etanol** [python/cpython#101668]
# Bug report

In 3.11 is not possible to build by running `./configure` with an empty prefix:

```
./configure --prefix=
```

After such configuration, running `make` fails with something similar to the following:

```
./_bootstrap_python ./Programs/_freeze_module.py abc ./Lib/abc.py Python/frozen_modules/abc.h
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/home/etanol/Python-3.11.1/Lib/site.py", line 79, in <module>
    PREFIXES = [sys.prefix, sys.exec_prefix]
                ^^^^^^^^^^
AttributeError: module 'sys' has no attribute 'prefix'
Makefile:1200: recipe for target 'Python/frozen_modules/abc.h' failed
```

## Possible explanation

The `sys` module [takes attributes like `sys.exec` and `sys.exec_prefix` from the `PyConfig` structure][1].  However, if any of those values is `NULL`, the [attribute does **not** seem to be defined][2].

During path calculation, the result of evaluating (the frozen version of) `getpath.py` [is copied back to `PyConfig`][3].  But [the `prefix` and similar fields][4] are treated [by converting `None` to `NULL`][5] (from [the C macro expansion][6]).

The prefix [indicated to `./configure`][7] is passed on [when compiling `getpath.c`][8].  But empty strings [are converted to `None`][9].  If the evaluation of (frozen) `getpath.py` assigns `None` to the `prefix` global variable (and similar) [what gets transferred back to `getpath.c`][10] ends up [becoming `NULL` in `PyConfig`][5].

I think an empty prefix worked in 3.10, and earlier, because the transition from [C compiler macro to Python value][11] preserved empty strings.  Empty C strings were converted to empty Python strings; but 3.11 converts [empty C strings to `None`][9].

[1]: /python/cpython/blob/955ba2839bc5875424ae745bfab53e880a9ace49/Python/sysmodule.c#L3097-L3103
[2]: /python/cpython/blob/955ba2839bc5875424ae745bfab53e880a9ace49/Python/sysmodule.c#L3088-L3091
[3]: /python/cpython/blob/955ba2839bc5875424ae745bfab53e880a9ace49/Modules/getpath.c#L946
[4]: /python/cpython/blob/955ba2839bc5875424ae745bfab53e880a9ace49/Python/initconfig.c#L1385-L1388
[5]: /python/cpython/blob/955ba2839bc5875424ae745bfab53e880a9ace49/Python/initconfig.c#L1210-L1212
[6]: /python/cpython/blob/955ba2839bc5875424ae745bfab53e880a9ace49/Python/initconfig.c#L1311-L1316
[7]: /python/cpython/blob/955ba2839bc5875424ae745bfab53e880a9ace49/Modules/getpath.c#L889
[8]: /python/cpython/blob/955ba2839bc5875424ae745bfab53e880a9ace49/Makefile.pre.in#L1243-L1246
[9]: /python/cpython/blob/955ba2839bc5875424ae745bfab53e880a9ace49/Modules/getpath.c#L609-L622
[10]: /python/cpython/blob/955ba2839bc5875424ae745bfab53e880a9ace49/Modules/getpath.py#L781
[11]: /python/cpython/blob/25196d6fb2c4d5d78b9b1c56207246d4de8dc83b/Modules/getpath.c#L1446

## Considerations

Using dummy values for `./configure --prefix` and then controlling installation target with `make DESTDIR=...` is a fairly common practice when creating binary packages.  It's very convenient as a way to build software inside _sandboxed_ environments.

However, it is certainly arguable that allowing for an empty prefix may not be of interest (it's just as common to run `./configure --prefix=/`).

It is also beyond my understanding to determine if the fix should be about preserving empty strings in the C to Python conversion or perhaps the logic in `getpath.py` should be modified with a last resort check to avoid setting `prefix` (and similar) to `None`.

# Your environment

- CPython versions tested on: 3.11.1
- Operating system and architecture: Ubuntu 18.04 x86-64

**Comment by ruivlea** [comment]
This issue still exist in 3.11.5.
python cannot be build and installed to / with configure --prefix= or --prefix=/
Any workaround?

**Comment by etanol** [comment]
Yes, I managed to work around this by indicating `prefix` in `make` commands.  Like so:

```
./configure --prefix=  --other-options …
make prefix=.
make prefix=/. DESTDIR=actual/target install
```

This works because my build automation performs additional manipulations after.  But at least the places affected by `prefix` remain as clean as possible.
