### ISSUE TITLE
Segfault when supplying too many arguments to int()

### ISSUE THREAD

**Issue by pschanely** [python/cpython#114210]
# Crash report

### What happened?

Python 3.12 raises the expected TypeError `int() takes at most 2 arguments (3 given)` for the code below, but it causes a segfault in 3.13.0a2:

```python
Python 3.13.0a2 (main, Jan  3 2024, 11:50:58) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> int("42", 10, 12)
zsh: segmentation fault  python
```

### CPython versions tested on:

CPython 3.13.0a2

### Operating systems tested on:

macOS

### Output from running 'python -VV' on the command line:

Python 3.13.0a2 (main, Jan  3 2024, 11:50:58) [Clang 15.0.0 (clang-1500.1.0.2.5)]

**Comment by Eclips4** [comment]
Hello!
There's the same problem as in #114050.
Closing as duplicate.

**Comment by hugovk** [comment]
And to confirm, bisecting between v3.13.a1 (TypeError) and v3.13.a2 (segmentation fault) gives the same 0887b9ce8b5b4f9ecdef014b9329da78a46c9f42:

```
0887b9ce8b5b4f9ecdef014b9329da78a46c9f42 is the first bad commit
commit 0887b9ce8b5b4f9ecdef014b9329da78a46c9f42
Date:   Thu Nov 2 15:07:47 2023 +0000

    GH-109369 Add vectorcall to `PyLong_Type` (GH-111642)

 Objects/longobject.c | 25 +++++++++++++++++++++++++
 1 file changed, 25 insertions(+)
```
