### ISSUE TITLE
gh-105716 breaks greenlet/eventlet

### ISSUE THREAD

**Issue by doko42** [python/cpython#112826]
# Bug report

### Bug description:

gh-105716 breaks greenlet/eventlet, which apparently was working with the 3.12.0 release.
this is greenlet 3.0.1, plus eventlet 0.33.3 plus the python3.12 for eventlet taken from
https://src.fedoraproject.org/rpms/python-eventlet/tree/rawhide

```pytb
Traceback (most recent call last):
  File "/home/packages/12/python-eventlet-0.33.3/tests/isolated/patcher_existing_locks_late.py", line 20, in <module>
    eventlet.monkey_patch()
  File "/home/packages/12/python-eventlet-0.33.3/eventlet/patcher.py", line 294, in monkey_patch
    modules_to_patch += modules_function()
                        ^^^^^^^^^^^^^^^^^^
  File "/home/packages/12/python-eventlet-0.33.3/eventlet/patcher.py", line 480, in _green_thread_modules
    from eventlet.green import threading
  File "/home/packages/12/python-eventlet-0.33.3/eventlet/green/threading.py", line 22, in <module>
    eventlet.patcher.inject(
  File "/home/packages/12/python-eventlet-0.33.3/eventlet/patcher.py", line 109, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/threading.py", line 40, in <module>
    _is_main_interpreter = _thread._is_main_interpreter
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'eventlet.green.thread' has no attribute '_is_main_interpreter'

---
FAIL
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-112850
* gh-112853

**Comment by ericsnowcurrently** [comment]
FTR:

original PR: gh-112661
3.12 backport: gh-110707

**Comment by ericsnowcurrently** [comment]
@Yhg1s, should this block 3.12.1?  I expect to have a fix up shortly.

**Comment by ericsnowcurrently** [comment]
To be clear, I am not planning on any actual fix in main (3.13+).  There will only be a "What's New" entry.  If an app or library is replacing the `_thread` module then they already know they need to provide everything the stdlib module does, including the "private" attributes (especially those used by `threading`).  This seems like a fairly rare case so I'm okay with helping any such libraries with their fixes.

(The situation is different for 3.12, where 3.12.0 was already released and the change in gh-110707 introduced a regression.  Thus a fix was needed for 3.12.1.)

In addition to the 3.12 fix, I'm planning on making sure gevent/eventlet gets fixed upstream.

**Comment by Eclips4** [comment]
Thanks for the fix Eric!
