### ISSUE TITLE
`multiprocessing.Pool` lambda initializer raises PicklingError in 3.14

### ISSUE THREAD

**Issue by bgilbert** [python/cpython#142249]
# Bug report

### Bug description:

```python
import multiprocessing
multiprocessing.Pool(None, lambda: None)
```

This works in Python versions up to 3.13.9, but fails in 3.14.0:

```console
AttributeError: module '__main__' has no attribute '<lambda>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bgilbert/tmp/t/pool.py", line 2, in <module>
    multiprocessing.Pool(None, lambda: None)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.14/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
                context=self.get_context())
  File "/usr/lib64/python3.14/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib64/python3.14/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
                                        self._processes,
                                        ^^^^^^^^^^^^^^^^
    ...<3 lines>...
                                        self._maxtasksperchild,
                                        ^^^^^^^^^^^^^^^^^^^^^^^
                                        self._wrap_exception)
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.14/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
    ~~~~~~~^^
  File "/usr/lib64/python3.14/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ~~~~~~~~~~~^^^^^^
  File "/usr/lib64/python3.14/multiprocessing/context.py", line 300, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.14/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib64/python3.14/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
    ~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib64/python3.14/multiprocessing/popen_forkserver.py", line 47, in _launch
    reduction.dump(process_obj, buf)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.14/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7ff55732b480>: it's not found as __main__.<lambda>
when serializing tuple item 2
when serializing dict item '_args'
when serializing multiprocessing.context.ForkServerProcess state
when serializing multiprocessing.context.ForkServerProcess object
```

### CPython versions tested on:

3.14

### Operating systems tested on:

Linux

**Comment by duaneg** [comment]
This is because the default multiprocessing start method changed on Linux in that version. It is now `forkserver`, which requires pickling the state, where previously it was `fork` that does not. Calling `multiprocessing.set_start_method('fork')` will fix it:
```python
import multiprocessing as mp
mp.set_start_method('fork')
with mp.Pool(None, lambda: None): pass
```
