### ISSUE TITLE
Build failure without thread local support

### ISSUE THREAD

**Issue by velemas** [python/cpython#127865]
# Bug report

### Bug description:

When building environments without thread local support, this build failure occurs:
```
~/cpython-3.13.1/Python/import.c:750: error: argument of type "PyMutex" is incompatible with parameter of type "PyThread_type_lock"
      PyThread_acquire_lock(EXTENSIONS.mutex, WAIT_LOCK);
                            ^
~/cpython-3.13.1/Python/import.c:760: error: argument of type "PyMutex" is incompatible with parameter of type "PyThread_type_lock"
      PyThread_release_lock(EXTENSIONS.mutex);
                            ^
~/cpython-3.13.1/Python/import.c:769: error: argument of type "PyMutex" is incompatible with parameter of type "PyThread_type_lock"
      PyThread_acquire_lock(EXTENSIONS.mutex, WAIT_LOCK);
                            ^
~/cpython-3.13.1/Python/import.c:774: error: argument of type "PyMutex" is incompatible with parameter of type "PyThread_type_lock"
      PyThread_release_lock(EXTENSIONS.mutex);
```
The issue is caused by incomplete change introduced with the commit 628f6eb from the PR https://github.com/python/cpython/pull/112207.

### CPython versions tested on:

3.13

### Operating systems tested on:

Other

### Linked PRs
* gh-127866
* gh-127882

**Comment by ZeroIntensity** [comment]
I suspect the fix is to just change that to `PyMutex_Lock`, but which system is this? We explicitly [dropped support](https://peps.python.org/pep-0011/#no-longer-supported-platforms) for systems without multithreading back in 3.7, but I'm not sure if the ability to have thread-locals falls under that umbrella.

**Comment by velemas** [comment]
@ZeroIntensity thread-locals are not necessary for multithreading.
The affected system is a mainframe.

**Comment by colesbury** [comment]
It's good to fix the erroneous calls to `PyThread_acquire_lock`, but I think you'll still run into:

https://github.com/python/cpython/blob/487fdbed40734fd7721457c6f6ffeca03da0b0e7/Python/pystate.c#L74-L78

**Comment by velemas** [comment]
@colesbury It is the local mainframe system compiler based on LLVM with C11 support but all C11 threading features are still missing there.

**Comment by velemas** [comment]
> It's good to fix the erroneous calls to `PyThread_acquire_lock`, but I think you'll still run into:
> 
> https://github.com/python/cpython/blob/487fdbed40734fd7721457c6f6ffeca03da0b0e7/Python/pystate.c#L74-L78

That part is covered with local patching by falling back to PyThread_tss_*() API as the comment suggests.

**Comment by ZeroIntensity** [comment]
What do you mean by "local patching"? The thread state doesn't fall back to `PyThread_tss` (it's a TODO comment).

**Comment by velemas** [comment]
@ZeroIntensity There is a port of python for the mainframe and that part is covered with the port patches from the mainframe maintainers (incl. me).

**Comment by colesbury** [comment]
Thanks!

**Comment by ZeroIntensity** [comment]
Do you think it's worth trying to fix (and test) building Python without thread locals? Using `PyThread_tss` shouldn't be too difficult for the thread state, but I'm not sure what other cases exist.

**Comment by colesbury** [comment]
I think the opposite: we should get rid of `HAS_THREAD_LOCAL` and move the `#error` message to [`pyport.h`](https://github.com/python/cpython/blob/ba2d2fda93a03a91ac6cdff319fd23ef51848d51/Include/pyport.h#L500-L519):

* All the [supported platforms](https://peps.python.org/pep-0011/#support-tiers) support thread local variables
* C11 (and C23) have thread local as part of the language
* We require C11 since Python 3.11

I don't think a `PyThread_tss` fallback is worth the maintenance effort just to support unnamed hardware from an unnamed company 👁️ 🐝 M.

There was a proposal [WG14 N2291](http://www5.open-std.org/JTC1/SC22/WG14/www/docs/n2291.htm) for C23 to make `_Thread_local` dependent on `__STDC_NO_THREADS__`. It wasn't accepted. (I bet you can guess the author's company!)

**Comment by ZeroIntensity** [comment]
Now I'm curious what "unnamed company" has against thread locals! 

Anyways, removing the macro seems reasonable if everything we support must have thread locals. It might be worth deprecating `PyThread_tss` too.

**Comment by velemas** [comment]
> I think the opposite: we should get rid of `HAS_THREAD_LOCAL` and move the `#error` message to [`pyport.h`](https://github.com/python/cpython/blob/ba2d2fda93a03a91ac6cdff319fd23ef51848d51/Include/pyport.h#L500-L519):
> 
>     * All the [supported platforms](https://peps.python.org/pep-0011/#support-tiers) support thread local variables
> 
>     * C11 (and C23) have thread local as part of the language
> 
>     * We require C11 since Python 3.11
> 
> 
> I don't think a `PyThread_tss` fallback is worth the maintenance effort just to support unnamed hardware from an unnamed company 👁️ 🐝 M.
> 
> There was a proposal [WG14 N2291](http://www5.open-std.org/JTC1/SC22/WG14/www/docs/n2291.htm) for C23 to make `_Thread_local` dependent on `__STDC_NO_THREADS__`. It wasn't accepted. (I bet you can guess the author's company!)

It is not 👁️ 🐝 M. The mainframe system was originally developed by Siemens. But I guess all mainframes have their hardships supporting thread locals.
