### ISSUE TITLE
Tkinter fails to build with Tcl 9.0 due to `Tcl_AppInit()` undeclared

### ISSUE THREAD

**Issue by chrstphrchvz** [python/cpython#104363]
Since Tcl 8.0.5 (https://github.com/tcltk/tcl/commit/17481a9360ea758b106cce6d9ec42c575a877eb5), tcl.h has clarified that `Tcl_AppInit()` is not an exported Tcl library function, and declares `Tcl_AppInit()` for compatibility/convenience only:

```c
/*
 *----------------------------------------------------------------------------
 * Convenience declaration of Tcl_AppInit for backwards compatibility. This
 * function is not *implemented* by the tcl library, so the storage class is
 * neither DLLEXPORT nor DLLIMPORT.
 */

extern Tcl_AppInitProc Tcl_AppInit;
```

This declaration is deprecated in Tcl 8.7 and removed in Tcl 9.0. Without it, _tkinter.c will fail to build if the compiler treats implicit function declarations as errors:

```
./Modules/_tkinter.c:713:9: error: call to undeclared function 'Tcl_AppInit'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
    if (Tcl_AppInit(v->interp) != TCL_OK) {
        ^
./Modules/_tkinter.c:713:9: note: did you mean 'Tcl_Init'?
/Users/user/tcl90p/include/tclDecls.h:513:13: note: 'Tcl_Init' declared here
EXTERN int              Tcl_Init(Tcl_Interp *interp);
                        ^
```

Although it seems possible to have _tkinter.c declare `Tcl_AppInit()` when tcl.h does not, I am not familiar enough with `Tcl_AppInit()` usage to know whether that is a good solution. From reading the [`Tcl_AppInit()` documentation](https://www.tcl-lang.org/man/tcl8.7/TclLib/AppInit.html), it sounds like Tkinter could instead rename its `Tcl_AppInit()` in tkappinit.c to something else, which it then always declares in _tkinter.c.

**Comment by terryjreedy** [comment]
@serhiy-storchaka This issue is about patching _tkinter.

**Comment by serhiy-storchaka** [comment]
Tkinter builds now with Tcl 9.0. I leave this issue open for the case if we find better solution.

**Comment by serhiy-storchaka** [comment]
The build failure itself was fixed in #112681 (gh-112681) by adding the missing declaration under `#if TK_MAJOR_VERSION >= 9`, and Tkinter has built against Tcl/Tk 9.0/9.1 since. I left this open in case a cleaner approach emerged, but on review the minimal declaration is the right one.

The tempting alternative — rename our `Tcl_AppInit` to a private name and drop the version guard — would break a documented customization seam. `configure` sets `-DWITH_APPINIT=1` on every standard build, so the live `Tcl_AppInit` is the one in `Modules/tkappinit.c`, which is the hook for statically linking Tcl/Tk packages (`-DWITH_TIX`/`WITH_BLT`/`WITH_TOGL`/…). Renaming it silently breaks anyone patching that file.

@dkfellows is right that the name isn't special (Tcl only calls it from `Tcl_Main`, which we don't use) — which is exactly why declaring and calling our own is fine. And we can't reduce the call to a bare `Tcl_Init`, since our `Tcl_AppInit` also handles `_tkinter_skip_tk_init` and `Tkinter_TkInit`.

So closing as completed. Retiring `tkappinit.c`/`WITH_APPINIT` altogether (Tix is gone in Tcl 9; BLT/Togl/static-PIL are long dead) is worth considering, but that's a separate cleanup.
