### ISSUE TITLE
`test_cppext.TestCPPExt.test_build` broken on `AMD64 FreeBSD PR` buildbot

### ISSUE THREAD

**Issue by mpage** [python/cpython#127885]
# Bug report

### Bug description:

First seen on https://buildbot.python.org/#/builders/1228/builds/423/. The failure looks like its coming from:

```
In file included from extension.cpp:9:
In file included from /buildbot/buildarea/pull_request.ware-freebsd/build/Include/Python.h:74:
/buildbot/buildarea/pull_request.ware-freebsd/build/Include/refcount.h:380:53: error: use of undeclared identifier 'UINT32_MAX'
380 |     if (op->ob_refcnt_full <= 0 || op->ob_refcnt > (UINT32_MAX - (1<<20))) {
    |                                                     ^
1 error generated.
error: command '/usr/bin/cc' failed with exit code 1
error: subprocess-exited-with-error
```

The use of `UINT32_MAX` here was introduced in https://github.com/python/cpython/pull/127797. 

cc @markshannon 

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

**Comment by mpage** [comment]
Already a PR up to fix this.
