### ISSUE TITLE
PGO/LTO Build Fails With -O0

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#128042]
# Bug report

### Bug description:

fails: `./configure CFLAGS=-O0 --enable-optimizations --with-lto`
succeeds: `./configure CFLAGS=-O1 --enable-optimizations --with-lto`

It fails when it runs the tests to build the profile.  The problematic test is `TestLRUC.test_lru_recursion` in Lib/test/test_functools.py.  It runs out of stack at well below the expected limit.  `Py_C_RECURSION_LIMIT` is set to 10000.  The test runs a simple recursive fibonacci function starting at 2857 (`limit*2//7`).  It keeps crashing with smaller values, down to about 450.  I'm not sure why the combination of PGO and `-O0` special in this regard.  (FYI, my build toolchain is probably a bit outdated, but I'm not sure that's a significant factor.)

I can think of several solutions here:

* "don't do that!": document that `-O0` should not be combined with `--enable-optimizations` ([docs](https://docs.python.org/3/using/configure.html#cmdoption-enable-optimizations), maybe [devguide](https://devguide.python.org/getting-started/setup-building/#optimization))
* print a warning in `configure` with that combination
* lower `Py_C_RECURSION_LIMIT` with that combination

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-137651
* gh-137975

**Comment by taegyunkim** [comment]
It doesn't even build on my ubuntu 22.04 with gcc 11.4.0 and libc 2.35 when `CFLAGS=-O0` is set. 

Last few lines from when I tried `./configure CFLAGS=-O0 --enable-optimizations --with-lto` and `make -s -j $(nproc)`

```
/usr/bin/ld: /tmp/cc2jZgIm.ltrans1.ltrans.o:(.data.rel.local+0x1c19f0): undefined reference to `.L343'
/usr/bin/ld: /tmp/cc2jZgIm.ltrans1.ltrans.o:(.data.rel.local+0x1c19f8): undefined reference to `.L344'
/usr/bin/ld: /tmp/cc2jZgIm.ltrans1.ltrans.o:(.data.rel.local+0x1c1a00): undefined reference to `.L345'
/usr/bin/ld: /tmp/cc2jZgIm.ltrans1.ltrans.o:(.data.rel.local+0x1c1a08): undefined reference to `.L346'
/usr/bin/ld: /tmp/cc2jZgIm.ltrans1.ltrans.o:(.data.rel.local+0x1c1a10): undefined reference to `.L347'
/usr/bin/ld: /tmp/cc2jZgIm.ltrans1.ltrans.o:(.data.rel.local+0x1c1a18): undefined reference to `.L348'
/usr/bin/ld: /tmp/cc2jZgIm.ltrans1.ltrans.o:(.data.rel.local+0x1c1a20): undefined reference to `.L349'
/usr/bin/ld: /tmp/cc2jZgIm.ltrans1.ltrans.o:(.data.rel.local+0x1c1a28): undefined reference to `.L350'
/usr/bin/ld: /tmp/cc2jZgIm.ltrans1.ltrans.o:(.data.rel.local+0x1c1a30): undefined reference to `.L351'
/usr/bin/ld: /tmp/cc2jZgIm.ltrans1.ltrans.o:(.data.rel.local+0x1c1a38): undefined reference to `.L352'
/usr/bin/ld: /tmp/cc2jZgIm.ltrans1.ltrans.o:(.data.rel.local+0x1c1a40): undefined reference to `.L353'
/usr/bin/ld: /tmp/cc2jZgIm.ltrans1.ltrans.o:(.data.rel.local+0x1c1a48): undefined reference to `.L354'
/usr/bin/ld: /tmp/cc2jZgIm.ltrans1.ltrans.o:(.data.rel.local+0x1c1a50): undefined reference to `.L355'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1927: Programs/_freeze_module] Error 1
make[1]: *** [Makefile:1007: profile-gen-stamp] Error 2
make: *** [Makefile:1019: profile-run-stamp] Error 2
```



I created PRs to udpate docs as linked in the PR, and to update [devguide](https://github.com/python/devguide/pull/1628).

**Comment by AA-Turner** [comment]
Are `CFLAGS` inherited from some other process here? It seems straightforward not to both enable and disable optimisations at the same time, doing so will produce unexpected results.
