### PR TITLE
gh-129280: Avoid cyclic reference in contextlib.contextmanager

### PR DESCRIPTION
**Pull request by user202729**
By deleting the cyclic reference between the frame object and the exception object, this allows the objects to be deleted more quickly (it doesn't need to wait until the next GC cycle)

This also has the practical impact of some packages (cysignals) using reference counting to detect whether the exception has been handled, which breaks in the presence of this situation. https://github.com/sagemath/sage/pull/39142

* Issue: gh-129280

### CODE REVIEW

**Review by ZeroIntensity — COMMENTED** [review]
At an overview:

- This seems issue-worthy to me; could you make one, and then link to it in the PR title?
- Per the bot, we do need a blurb entry, as this is a user-facing change.
- A test case would be good too (see [the devguide](https://devguide.python.org/testing/)).

However, going back to the use-case:

> This also has the practical impact of some packages (cysignals) using reference counting to detect whether the exception has been handled

I'd be *very* careful with that. We don't have any guarantees about reference counting, especially with built-in objects. (For example, on the free-threaded build, we have plenty of reference counting hacks that allow for multithreaded scalability--I suspect this kind of thing would break over there.)

**Comment by user202729** [comment]
> We don't have any guarantees about reference counting,

I know that very well. But…

6 years ago, there was a difficult to debug issue with SageMath https://github.com/sagemath/sage/issues/24986 , and the developers concluded using that hacky reference counting solution is the best available workaround.

Turns out it causes additional issues later: https://github.com/sagemath/sage/issues/39224

There exists a better solution, see  https://github.com/sagemath/cysignals/issues/215#issuecomment-2611404321 , but while it is not yet implemented (there are a lot of places that need to be changed in the code base) I try to make the best of what is available.

**Comment by ZeroIntensity** [comment]
> (in the meantime, I'll try to figure out how to write test case and blurb, but I'd appreciate any help.)

Feel free to tag me if you need any help. The devguide should have everything you need, though :)

File: Lib/contextlib.py [hunk 1]
```diff
@@ -164,7 +164,9 @@ def __exit__(self, typ, value, traceback):
                 # Suppress StopIteration *unless* it's the same exception that
                 # was passed to throw().  This prevents a StopIteration
                 # raised inside the "with" statement from being suppressed.
-                return exc is not value
+                result = exc is not value
+                del exc, value  # avoid cyclic reference
```
Comment (graingert) [inline Lib/contextlib.py:168]: You'll need to make the appropriate change in asynccontextmanager, and add a test

Comment (serhiy-storchaka) [reply Lib/contextlib.py:168]: I do not think that this is the right fix. Should not all local variables be cleared after leaving the function? If they are not, we have a larger issue.

Comment (graingert) [reply Lib/contextlib.py:168]: the traceback of the exception refers to the local variables

Comment (graingert) [reply Lib/contextlib.py:168]: I think the fix here is to wrap this whole `__exit__` in a:

```python
try:
    ...
finally:
    del value, traceback
```

exc should be cleared automatically by leaving the `except` block

With a test case this should be a lot clearer, (have a look at the cyclic exception tests in test_taskgroup, (the ones that call no_other_refs)

Comment (sobolevn) [reply Lib/contextlib.py:168]: @graingert or maybe this should be done one lever higher? Do other `__exit__`s have the same problem?

I agree with @serhiy-storchaka, this fix is not correct.

Comment (graingert) [reply Lib/contextlib.py:168]: It would be pretty magical to automatically delete value and traceback from every `__exit__` and `__aexit__`

Comment (serhiy-storchaka) [reply Lib/contextlib.py:168]: Why this was not an issue in 3.11?

I agree that `finally` with `del`s is better solution, but we should look if there is more fundamental issue, which affects not only `contextmanager`.

Comment (user202729) [reply Lib/contextlib.py:168]: I don't entirely know why it was not an issue in Python 3.11, but concretely, if you add `print(self.__traceback__.tb_frame.f_back.f_locals)` in `__del__` method, in Python 3.12 it prints out `{ ... 'value': MyException() ... }` while in Python 3.11 it prints out `AttributeError: 'NoneType' object has no attribute 'f_locals'`.

**Comment by user202729** [comment]
Feel best if I leave this as draft until I figure out what's the root cause of the change in behavior Python 3.11 and Python 3.12.

**Comment by user202729** [comment]
Bisecting results in 1e197e63e21f77b102ff2601a549dda4b6439455 being the first bad commit.

Seems to make sense? If more references to frames are added then it's more likely to create cyclic references…?

#96421

**Comment by user202729** [comment]
More investigation shows the frame object has `f_back` cleared when the function exits in Python 3.11, while this is not the case in Python 3.12.

I haven't fully understood what the linked pull request does yet, but maybe if only ensure the shim frame is cleared without clearing the actual frame…?

@markshannon Any idea about this?

<details><summary>Code</summary>

```python
from contextlib import contextmanager

class MyException(Exception):
	def __del__(self):
		print(self.__traceback__.tb_frame.f_back)
		print("deleted")

@contextmanager
def f():
	try:
		yield
	except MyException as e:
		global g
		g = e
		print(e.__traceback__.tb_frame.f_back)

with f():
	raise MyException()

print(g.__traceback__.tb_frame.f_back)  # ⟵ this prints None in Python 3.11 and <frame…> in Python 3.12

print("done")
```

</details>

**Comment by serhiy-storchaka** [comment]
I think that this PR (which likely will be closed in favor of more general solution) is not the best place for discussion.
