### ISSUE TITLE
Getting error LNK2001 in python3.12 with APIs - PyUnicode_FromUnicode, PyUnicode_GET_SIZE and PyUnicode_AS_UNICODE

### ISSUE THREAD

**Issue by bchoudhary6415** [python/cpython#115394]
# Bug report

### Bug description:

I'm building my python extension with python3.12
The above said APIs are working fine with python 3.11.

As I can see from the documentation that those APIs are removed from python3.12 now, but didn't get the proper replacement of those APIs.
I'm getting below error, while compiling the code -
Getting error that - ibm_db.obj : error LNK2001: unresolved external symbol PyUnicode_FromUnicode
Getting error that - ibm_db.obj : error LNK2001: unresolved external symbol PyUnicode_GET_SIZE
Getting error that - ibm_db.obj : error LNK2001: unresolved external symbol PyUnicode_AS_UNICODE

Please provide me the proper solution, what to use instead of unsupported APIs?

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, Windows

**Comment by bchoudhary6415** [comment]
I have taken help from below link 
https://docs.python.org/3.10/whatsnew/3.3.html?highlight#deprecated-functions-and-types-of-the-c-api
for the replacement of PyUnicode_AS_UNICODE, PyUnicode_GET_SIZE and PyUnicode_FromUnicode APIs.
Closing this issue.

Thanks
