### ISSUE TITLE
PyObject_New breaks by the commit 7ad6f74fcf9db1ccfeaf0986064870d8d3887300

### ISSUE THREAD

**Issue by trcrsired** [python/cpython#94185]
/usr/local/include/python3.12/objimpl.h:134:46: error: expected ')' before '_PyObject_New'
  134 | #define PyObject_New(type, typeobj) ((type *)_PyObject_New(typeobj))
      |                                     ~        ^~~~~~~~~~~~~
7ad6f74fcf9db1ccfeaf0986064870d8d3887300

This is not working for g++ 13

**Comment by vstinner** [comment]
Oh no, writing correct macros is so complicated :-( I wrote PR #94234 to fix this issue.

cc @erlend-aasland

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/94234

**Comment by vstinner** [comment]
Thanks for reporting the issue! It's great that you catched the issue early, so it could be fixed quickly ;-) I added unit tests to prevent future similar regressions. Sadly, the C API is still not fully tested, as you can see.
