### ISSUE TITLE
Python 3.12.3 -> 3.12.4 breaks use of `create_autospec(X, spec_set=True, name="X")` 

### ISSUE THREAD

**Issue by ShapingView** [python/cpython#120732]
# Bug report

### Bug description:

Hello, thanks for the work you do!

My issue: Updating from 3.12.3 to 3.12.4 breaks many elements in my test suite. We use the `name=` argument to better understand log messages once a test with many objects fails.

This works with 3.12.3, but crashes with 3.12.4. The issue might have been introduced with this fix: https://github.com/python/cpython/commit/23ba96e2433d17e86f4770a64b94aaf9ad22a25b

### Code example

File `autospec_test.py`:

```python
import unittest
from unittest.mock import create_autospec

class X: ...

class TestX(unittest.TestCase):
    def test_x(self):
        mock = create_autospec(X, spec_set=True, name="X")


if __name__ == "__main__":
    unittest.main()
```

#### python 3.12.3

```
python autospec_test.py
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```
#### python 3.12.4

```pytb
python autospec_test.py
E
======================================================================
ERROR: test_x (__main__.TestX.test_x)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../autospec_test.py", line 10, in test_x
    mock = create_autospec(X, spec_set=True, name="X")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/unittest/mock.py", line 2823, in create_autospec
    mock.configure_mock(**kwargs)
  File "/usr/local/lib/python3.12/unittest/mock.py", line 650, in configure_mock
    setattr(obj, final, val)
  File "/usr/local/lib/python3.12/unittest/mock.py", line 774, in __setattr__
    raise AttributeError("Mock object has no attribute '%s'" % name)
AttributeError: Mock object has no attribute 'name'

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, (CI pipelines failed on windows, too – didn't test this example, though.)

### Linked PRs
* gh-120737
* gh-120760
* gh-120761

**Comment by hugovk** [comment]
> The issue might have been introduced with this fix: https://github.com/python/cpython/commit/23ba96e2433d17e86f4770a64b94aaf9ad22a25b

Git bisect also points to the same commit:

```
23ba96e2433d17e86f4770a64b94aaf9ad22a25b is the first bad commit
commit 23ba96e2433d17e86f4770a64b94aaf9ad22a25b
Author: Miss Islington (bot) <31488909+miss-islington@users.noreply.github.com>
Date:   Thu May 2 20:01:17 2024 +0200

    [3.12] gh-90848: Fixed create_autospec ignoring configure_mock style kwargs (GH-118163) (#118517)

    gh-90848: Fixed create_autospec ignoring configure_mock style kwargs (GH-118163)
    (cherry picked from commit b28a3339e4c63ea3a801dba9bbbc6af5af42c3a0)

    Co-authored-by: infohash <46137868+infohash@users.noreply.github.com>

 Lib/test/test_unittest/testmock/testmock.py          | 13 +++++++++++++
 Lib/unittest/mock.py                                 | 20 ++++++++++++--------
 .../2024-04-22-21-54-12.gh-issue-90848.5jHEEc.rst    |  1 +
 3 files changed, 26 insertions(+), 8 deletions(-)
 create mode 100644 Misc/NEWS.d/next/Library/2024-04-22-21-54-12.gh-issue-90848.5jHEEc.rst
bisect found first bad commit
```

This is from backport PR https://github.com/python/cpython/pull/118517, `main` PR https://github.com/python/cpython/pull/118163, and issue https://github.com/python/cpython/issues/90848.

cc @infohash and @cjw296.

**Comment by nineteendo** [comment]
Can this be closed?
