### PR TITLE
bpo-38684: haslib: fix build when Blake2 not enabled in OpenSSL

### PR DESCRIPTION
**Pull request by commodo**
This was caught via OpenWrt's build, when upgrading to 3.8.
By default, Blake2 is not enabled in OpenWrt's OpenSSL.
Not sure if this is an issue in OpenSSL or Python or both.

After digging through the _hashopenssl.c, it seems that the check for
Blake2 being enabled/present in OpenSSL is not consistent with how OpenSSL
does it.

I guess this issue happens when Blake2 is present, but not enabled.
While the previous code was checking whether it is present.

Error is:
```
Modules/_hashopenssl.c:220:22: error: implicit declaration of function 'EVP_blake2s256'; did you mean 'SN_blake2s256'? [-Werror=implicit-function-declaration]
             digest = EVP_blake2s256();
                      ^~~~~~~~~~~~~~
                      SN_blake2s256
Modules/_hashopenssl.c:220:20: warning: assignment to 'const EVP_MD *' {aka 'const struct evp_md_st *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
             digest = EVP_blake2s256();
Modules/_hashopenssl.c:223:22: error: implicit declaration of function 'EVP_blake2b512'; did you mean 'LN_blake2b512'? [-Werror=implicit-function-declaration]
             digest = EVP_blake2b512();
                      ^~~~~~~~~~~~~~
Modules/_hashopenssl.c:223:20: warning: assignment to 'const EVP_MD *' {aka 'const struct evp_md_st *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
             digest = EVP_blake2b512();
                    ^
```

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

https://bugs.python.org/issue38684

### CODE REVIEW

**Review by tiran — CHANGES_REQUESTED** [review]
I'm sure this is not compatible with OpenSSL 1.1.0 and 1.0.2. You need to check for both the presence of NID-blake2b512 and absence of OPENSSL_NO_BLAKE2.

**Comment by commodo** [comment]
> I'm sure this is not compatible with OpenSSL 1.1.0 and 1.0.2. You need to check for both the presence of NID-blake2b512 and absence of OPENSSL_NO_BLAKE2.

good point;
i hadn't thought of that;

**Comment by commodo** [comment]
Changelog v1 ->v2:
* change check for Blake2 from `#ifdef NID_blake2b512` -> `#if defined(NID_blake2b512) && !defined(OPENSSL_NO_BLAKE2)`

**Review by tiran — APPROVED** [review]
Thanks!
