### ISSUE TITLE
pandas 2.2.1 install fails in 3.13.0 using python:3-alpine3.19  docker image

### ISSUE THREAD

**Issue by andreish** [python/cpython#125108]
# Bug report

### Bug description:

see Dockerfile  to reproduce here: 
https://github.com/docker-library/python/issues/975

```
FROM python:3-alpine3.19

RUN apk add --no-cache bash curl wget python3-dev  alpine-sdk && mkdir -p /srv
WORKDIR /srv
RUN python -m venv .venv
RUN source .venv/bin/activate && pip install pandas==2.2.1
```

error log: 

```
143.3       cc -Ipandas/_libs/json.cpython-313-x86_64-linux-musl.so.p -Ipandas/_libs -I../../pandas/_libs -I../../../../pip-build-env-y21n8_kb/overlay/lib/python3.13/site-packages/numpy/core/include -I../../pandas/_libs/include -I/usr/local/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O3 -DNPY_NO_DEPRECATED_API=0 -DNPY_TARGET_VERSION=NPY_1_21_API_VERSION -fPIC -MD -MQ pandas/_libs/json.cpython-313-x86_64-linux-musl.so.p/src_vendored_ujson_python_JSONtoObj.c.o -MF pandas/_libs/json.cpython-313-x86_64-linux-musl.so.p/src_vendored_ujson_python_JSONtoObj.c.o.d -o pandas/_libs/json.cpython-313-x86_64-linux-musl.so.p/src_vendored_ujson_python_JSONtoObj.c.o -c ../../pandas/_libs/src/vendored/ujson/python/JSONtoObj.c
143.3       In file included from /usr/include/fortify/string.h:26,
143.3                        from ../../pandas/_libs/include/pandas/portable.h:12,
143.3                        from ../../pandas/_libs/include/pandas/vendored/ujson/lib/ultrajson.h:55,
143.3                        from ../../pandas/_libs/src/vendored/ujson/python/JSONtoObj.c:41:
143.3       /usr/include/fortify/stdlib.h:42:1: error: 'realpath' undeclared here (not in a function)
143.3          42 | _FORTIFY_FN(realpath) char *realpath(const char *__p, char *__r)
143.3             | ^~~~~~~~~~~
143.3       In file included from /usr/local/include/python3.13/Python.h:38,
143.3                        from ../../pandas/_libs/src/vendored/ujson/python/JSONtoObj.c:43:
143.3       /usr/include/fortify/stdlib.h: In function 'realpath':
143.3       /usr/include/fortify/stdlib.h:45:2: error: #error PATH_MAX unset. A fortified realpath will not work.
143.3          45 | #error PATH_MAX unset. A fortified realpath will not work.
143.3             |  ^~~~~

```

it used to work with PYTHON_VERSION 3.13.0rc3 .

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by ZeroIntensity** [comment]
It might be, but the error is from pandas' header files, so there's nothing that we can do about this. If there was a C API regression somewhere, then they should report *that* to us.
