### ISSUE TITLE
Build fails with gcc 9.4.0 after d3b1bb2

### ISSUE THREAD

**Issue by mdboom** [python/cpython#129141]
# Bug report

### Bug description:

gcc-9.4.0 (from Ubuntu 20.04) fails to build latest CPython main:

```
In file included from ./Modules/_ctypes/callproc.c:87:
./Modules/_ctypes/ctypes.h:12:72: error: missing binary operator before token "("                                          12 | #   if USING_APPLE_OS_LIBFFI && defined(__has_builtin) && __has_builtin(__builtin_available)                          | 
```

The first bad commit seems to be d3b1bb228c95.  Fix incoming.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-129142
