### ISSUE TITLE
Add macro `HAVE_OPENSSL_VERIFY_PARAM` to avoid invalid function declaration

### ISSUE THREAD

**Issue by 813ef2d5-9df6-4b6c-a0c8-45581d4cecdd** [python/cpython#75050]
BPO | [30867](https://bugs.python.org/issue30867)
--- | :---
Nosy | @tiran
Files | <li>[_ssl.patch](https://bugs.python.org/file46993/_ssl.patch "Uploaded as text/plain at 2017-07-06.11:37:12 by signal1587")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2017-09-06.14:04:09.876>
created_at = <Date 2017-07-06.11:37:12.782>
labels = ['expert-SSL', 'build']
title = 'Add macro `HAVE_OPENSSL_VERIFY_PARAM` to avoid invalid function declaration'
updated_at = <Date 2017-09-06.14:04:09.875>
user = 'https://bugs.python.org/signal1587'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-06.14:04:09.875>
actor = 'christian.heimes'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2017-09-06.14:04:09.876>
closer = 'christian.heimes'
components = ['SSL']
creation = <Date 2017-07-06.11:37:12.782>
creator = 'signal1587'
dependencies = []
files = ['46993']
hgrepos = []
issue_num = 30867
keywords = ['patch']
message_count = 2.0
messages = ['297825', '301470']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'signal1587']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30867'
versions = ['Python 2.7']
```

</p></details>

**Comment by 813ef2d5-9df6-4b6c-a0c8-45581d4cecdd** [comment]
Compile Python (2.7.13) on platform which has OpenSSL (\<0.9.8) will met error:

  /opt/Python-2.7.13/Modules/_ssl.c:177: error: syntax error before ‘*’ token

Since return type `X509_VERIFY_PARAM` got added to OpenSSL in version 0.9.8.

Surround the implementation of function `X509_STORE_get0_param` in (#ifdef HAVE_OPENSSL_VERIFY_PARAM ... #endif) guarantee to solve this problem.

**Comment by tiran** [comment]
OpenSSL 0.9.7 and earlier are no longer supported. In fact OpenSSL \< 1.0.2 is no longer maintained by upstream OpenSSL developers. 2.7 is known to work with recent releases such as 0.9.8zh. 0.9.7 is definitely out of scope.
