### PR TITLE
bpo-1635741: Port hashlib modules to multiphase init (PEP 489)

### PR DESCRIPTION
**Pull request by koubaa**
https://bugs.python.org/issue1635741

### CODE REVIEW

**Comment by koubaa** [comment]
@shihai1991 @vstinner @corona10 FYI.  The macOS tests look to be due to the following error which seems unrelated to my change:
> module 'test.support' has no attribute 'EnvironmentVarGuard'

**Comment by shihai1991** [comment]
> @shihai1991 @vstinner @corona10 FYI. The macOS test failure looks to be due to the following error which seems unrelated to my change:
> 
> > module 'test.support' has no attribute 'EnvironmentVarGuard'

Hm, this failure have no relation with your PR. It's weird. Some failed test cases have updated: https://github.com/python/cpython/blob/master/Lib/test/test_selectors.py#L540

**Comment by shihai1991** [comment]
The failed test cases have been fixed in https://github.com/python/cpython/commit/490c5426b1b23831d83d0c6b269858fb98450889
Can you do some  `git rebase` operation? MAYBE this operation can solve your probleam.

File: Modules/_blake2/blake2b_impl.c [hunk 1]
```diff
@@ -394,44 +394,18 @@ py_blake2b_dealloc(PyObject *self)
     PyObject_Del(self);
 }
 
+static PyType_Slot blake2b_type_slots[] = {
+    {Py_tp_dealloc, py_blake2b_dealloc},
```
Comment (vstinner) [inline Modules/_blake2/blake2b_impl.c]: When you convert a static type to a heap type, you have to modify its tp_dealloc slot to DECREF its type.

File: Modules/_blake2/blake2b_impl.c [hunk 2]
```diff
@@ -391,47 +391,24 @@ py_blake2b_dealloc(PyObject *self)
         PyThread_free_lock(obj->lock);
         obj->lock = NULL;
     }
+    PyTypeObject *tp = Py_TYPE(self);
+    Py_DECREF(tp);
```
Comment (vstinner) [inline Modules/_blake2/blake2b_impl.c]: Please move it after PyObject_Del().

File: Modules/_blake2/blake2module.c [hunk 3]
```diff
@@ -12,62 +12,53 @@
...
-};
-
 #define ADD_INT(d, name, value) do { \
     PyObject *x = PyLong_FromLong(value); \
     if (!x) { \
-        Py_DECREF(m); \
-        return NULL; \
+        return -1; \
     } \
     if (PyDict_SetItemString(d, name, x) < 0) { \
```
Comment (vstinner) [inline Modules/_blake2/blake2module.c]: There is a refleak (unrelated to your change): Py_DECREF(x) is also needed here.

File: Modules/_blake2/blake2module.c [hunk 4]
```diff
@@ -12,62 +12,53 @@
...
 {
-    PyObject *m;
-    PyObject *d;
+    Blake2State* st = blake2_get_state(m);
 
-    m = PyModule_Create(&blake2_module);
-    if (m == NULL)
-        return NULL;
+    st->blake2b_type = (PyTypeObject *)PyType_FromModuleAndSpec(
+        m, &blake2b_type_spec, NULL);
```
Comment (vstinner) [inline Modules/_blake2/blake2module.c]: This function can fail, you have to check for NULL. Same remark for other PyType_FromModuleAndSpec() calls below.

**Review by vstinner — CHANGES_REQUESTED** [review]
This PR is a little bit too large. Would you mind to restrict it to blake2 which is already complex enough?

Once this PR is merged, you can write a PR for sha3 which is complex. Then we can finish with remaining modules like md5 and sha1. Or publish all PR are once.

**Comment by koubaa** [comment]
@vstinner that's not a problem - I put each file in its own commit so I can easily submit separate PRs.  I'll submit one for sha3, one for blake2, and one with the remaining ones.  After breaking up and creating PRs for each I'll address your comments

**Comment by koubaa** [comment]
@vstinner 
- blake 2: https://github.com/python/cpython/pull/21856
- sha3: https://github.com/python/cpython/pull/21855
- everything else: I kept in this PR

Thanks for the review!

File: Modules/_blake2/blake2b_impl.c (hunk 2 above)
Comment (koubaa) [reply Modules/_blake2/blake2b_impl.c]: @vstinner For my own information what's the reason?  Is this because the ref count of self may hit 0 and it will be double freed?

File: Modules/_blake2/blake2module.c (hunk 4 above)
Comment (koubaa) [reply Modules/_blake2/blake2module.c]: Addressed in the blake2 PR

File: Modules/_blake2/blake2module.c (hunk 3 above)
Comment (koubaa) [reply Modules/_blake2/blake2module.c]: Addressed in the blake2 PR

File: Modules/_blake2/blake2b_impl.c (hunk 2 above)
Comment (koubaa) [reply Modules/_blake2/blake2b_impl.c]: Addressed in the blake2 PR

File: Modules/md5module.c [hunk 5]
```diff
@@ -462,40 +468,19 @@ static PyGetSetDef MD5_getseters[] = {
...
+    {Py_tp_dealloc, MD5_dealloc},
+    {Py_tp_methods, MD5_methods},
+    {Py_tp_getset, MD5_getseters},
+    {0,0}
 };
 
+static PyType_Spec md5_type_spec = {
+    .name = "_md5.md5",
+    .basicsize =  sizeof(MD5object),
+    .flags = Py_TPFLAGS_DEFAULT,
```
Comment (vstinner) [inline Modules/md5module.c:487]: Can you please add a comment like:

```
    // Using PyType_GetModuleState() on this type is safe since
    // it cannot be subclassed: it does not have the Py_TPFLAGS_BASETYPE flag.
```

(I let you reformat it, if needed.)

Please add the same comment to other types converted to heap types and also using PyType_GetModuleState().

File: Modules/md5module.c [hunk 6]
```diff
@@ -551,35 +537,47 @@ static struct PyMethodDef MD5_functions[] = {
...
+
+    st->md5_type = (PyTypeObject *)PyType_FromModuleAndSpec(
+        m, &md5_type_spec, NULL);
+
+    if (st->md5_type == NULL) {
+        return -1;
+    }
+
+    //cannot use PyModule_AddType becuase "MD5Type"
+    //isn't the same as _PyType_Name(st->md5_type)
```
Comment (vstinner) [inline Modules/md5module.c]: I am not sure that this comment is useful. If you want to keep it, just add a space after ``//``.

File: Modules/md5module.c [hunk 7]
```diff
@@ -462,40 +468,19 @@ static PyGetSetDef MD5_getseters[] = {
...
-    0,                  /*tp_clear*/
-    0,                  /*tp_richcompare*/
-    0,                  /*tp_weaklistoffset*/
-    0,                  /*tp_iter*/
-    0,                  /*tp_iternext*/
-    MD5_methods,        /* tp_methods */
-    NULL,               /* tp_members */
-    MD5_getseters,      /* tp_getset */
+static PyType_Slot md5_type_slots[] = {
+    {Py_tp_dealloc, MD5_dealloc},
```
Comment (vstinner) [inline Modules/md5module.c:478]: You have to DECREF the type if you convert a static type to a heap type.

Same comment for other types.

File: Modules/sha512module.c [hunk 8]
```diff
@@ -460,12 +463,13 @@ SHA512Type_copy_impl(SHAobject *self)
 /*[clinic end generated code: output=adea896ed3164821 input=9f5f31e6c457776a]*/
 {
     SHAobject *newobj;
+    SHA512State *st = PyType_GetModuleState(Py_TYPE(self));
```
Comment (vstinner) [inline Modules/sha512module.c]: This code is illegal if you are not sure that self is an instance of a SHA512 object. You should get the defining class using Argument Clinic instead. Something like "cls: defining_class", see Modules/posixmodule.c for example.

File: Modules/sha512module.c [hunk 9]
```diff
@@ -740,41 +709,59 @@ static struct PyMethodDef SHA_functions[] = {
...
-        NULL,
-        -1,
-        SHA_functions,
-        NULL,
-        NULL,
-        NULL,
-        NULL
-};
+    st->sha384_type = (PyTypeObject *)PyType_FromModuleAndSpec(
+        m, &sha512_sha384_type_spec, NULL);
```
Comment (vstinner) [inline Modules/sha512module.c:757]: You must check for failure explicitly.

**Comment by koubaa** [comment]
@vstinner I'm going on vacation so I'll come back to address you comment next week.

File: Modules/sha512module.c (hunk 9 above)
Comment (koubaa) [reply Modules/sha512module.c:757]: @vstinner see a few lines down, I check for NULL for st->sha384_type and st->sha512_type

File: Modules/sha512module.c (hunk 8 above)
Comment (koubaa) [reply Modules/sha512module.c]: @vstinner Done.

Btw - the [doc](https://docs.python.org/3/howto/clinic.html) for argument clinic contains something that is not possible with heap types:
>When you declare a class, you must also specify two aspects of its type in C: the type declaration you’d use for a pointer to an instance of this class, and a pointer to the PyTypeObject for this class.

File: Modules/md5module.c (hunk 6 above)
Comment (koubaa) [reply Modules/md5module.c]: @vstinner I'll remove it

File: Misc/NEWS.d/next/Core and Builtins/2020-08-10-16-11-32.bpo-1635741.O0d3ym.rst [hunk 10]
```diff
@@ -0,0 +1,3 @@
+Port :mod:`sha1` to multi-phase init
+Port :mod:`sha512` to multi-phase init
+Port :mod:`md5` to multi-phase init
```
Comment (vstinner) [inline Misc/NEWS.d/next/Core and Builtins/2020-08-10-16-11-32.bpo-1635741.O0d3ym.rst]: I propose:

```
Port :mod:`sha1`, :mod:`sha512` and :mod:`md5` extension modules
to multi-phase initialization (PEP 489).
```

File: Modules/md5module.c [hunk 11]
```diff
@@ -318,21 +318,28 @@ md5_done(struct md5_state *md5, unsigned char *out)
  * ------------------------------------------------------------------------
  */
 
-static PyTypeObject MD5type;
+typedef struct {
+    PyTypeObject* md5_type;
+} MD5State;
 
+static inline MD5State* md5_get_state(PyObject *module) {
```
Comment (vstinner) [inline Modules/md5module.c]: PEP 7 coding style:

```suggestion
static inline MD5State*
md5_get_state(PyObject *module)
{
```

Please apply the same change to other newly added functions.

File: Modules/md5module.c [hunk 12]
```diff
@@ -318,21 +318,28 @@ md5_done(struct md5_state *md5, unsigned char *out)
...
+    return (MD5object *)PyObject_New(MD5object, st->md5_type);
 }
 
-
 /* Internal methods for a hash object */
 
 static void
 MD5_dealloc(PyObject *ptr)
 {
+    Py_DECREF(Py_TYPE(ptr));
```
Comment (vstinner) [inline Modules/md5module.c]: Please DECREF the type at the end. See Modules/_abc.c dealloc function for example.

Same remark for other dealloc functions.

File: Modules/sha1module.c [hunk 13]
```diff
@@ -526,37 +516,76 @@ static struct PyMethodDef SHA1_functions[] = {
...
+
+    st->sha1_type = (PyTypeObject *)PyType_FromModuleAndSpec(
+        module, &sha1_type_spec, NULL);
+
+    if (st->sha1_type == NULL) {
+        return -1;
+    }
+
+    //cannot use PyModule_AddType becuase "SHA1Type"
+    //isn't the same as _PyType_Name(st->sha1_type)
```
Comment (vstinner) [inline Modules/sha1module.c]: This comment is not really useful, please remove it.

File: Modules/md5module.c [hunk 14]
```diff
@@ -549,37 +538,72 @@ static struct PyMethodDef MD5_functions[] = {
...
+    MD5State *st = md5_get_state(m);
+
+    st->md5_type = (PyTypeObject *)PyType_FromModuleAndSpec(
+        m, &md5_type_spec, NULL);
+
+    if (st->md5_type == NULL) {
+        return -1;
+    }
+
+    if (PyType_Ready(st->md5_type) < 0) {
```
Comment (vstinner) [inline Modules/md5module.c]: Hum, PyType_FromModuleAndSpec() create types which are already ready. This call was only useful for static types. You can now remove it.

File: Modules/sha512module.c (hunk 9 above)
Comment (vstinner) [reply Modules/sha512module.c:757]: Oh, right.

File: Modules/md5module.c (hunk 14 above)
Comment (koubaa) [reply Modules/md5module.c]: @vstinner I made this mistake in other places too, I'll try to remember this

File: Modules/md5module.c [hunk 15]
```diff
@@ -318,22 +318,31 @@ md5_done(struct md5_state *md5, unsigned char *out)
...
+    return (MD5object *)PyObject_New(MD5object, st->md5_type);
 }
 
-
 /* Internal methods for a hash object */
 
 static void
 MD5_dealloc(PyObject *ptr)
 {
+    PyObject *tp = Py_TYPE(ptr);
```
Comment (vstinner) [inline Modules/md5module.c]: Py_TYPE retunrs a `PyTypeObject *`:

```suggestion
    PyTypeObject *tp = Py_TYPE(ptr);
```

Same remark for other files.

File: Modules/md5module.c [hunk 16]
```diff
@@ -318,22 +318,31 @@ md5_done(struct md5_state *md5, unsigned char *out)
  * ------------------------------------------------------------------------
  */
 
-static PyTypeObject MD5type;
+typedef struct {
+    PyTypeObject* md5_type;
+} MD5State;
 
+static inline MD5State* md5_get_state(PyObject *module)
```
Comment (vstinner) [inline Modules/md5module.c]:
```suggestion
static inline MD5State*
md5_get_state(PyObject *module)
```

File: Misc/NEWS.d/next/Core and Builtins/2020-08-10-16-11-32.bpo-1635741.O0d3ym.rst [hunk 17]
```diff
@@ -0,0 +1 @@
+Port :mod:`sha1`, :mod:`sha512`, and :mod:`md5` to multi-phase init (PEP 489)
```
Comment (vstinner) [inline Misc/NEWS.d/next/Core and Builtins/2020-08-10-16-11-32.bpo-1635741.O0d3ym.rst]:
```suggestion
Port the :mod:`sha1`, :mod:`sha512`, and :mod:`md5` extension modules
to the multi-phase initialization API (:pep:`489`).
```

File: Modules/md5module.c [hunk 18]
```diff
@@ -549,37 +540,68 @@ static struct PyMethodDef MD5_functions[] = {
...
+}
+
+static void
+_md5_free(void *module)
+{
+    _md5_clear((PyObject *)module);
+}
 
 /* Initialize this module. */
+static int md5_exec(PyObject *m)
```
Comment (vstinner) [inline Modules/md5module.c]:
```suggestion
static int
md5_exec(PyObject *m)
```

File: Modules/sha1module.c [hunk 19]
```diff
@@ -295,13 +295,21 @@ sha1_done(struct sha1_state *sha1, unsigned char *out)
  * ------------------------------------------------------------------------
  */
 
-static PyTypeObject SHA1type;
+typedef struct {
+    PyTypeObject* sha1_type;
+} SHA1State;
 
+static inline SHA1State* sha1_get_state(PyObject *module)
```
Comment (vstinner) [inline Modules/sha1module.c]:
```suggestion
static inline SHA1State*
sha1_get_state(PyObject *module)
```

File: Modules/sha1module.c [hunk 20]
```diff
@@ -526,37 +518,71 @@ static struct PyMethodDef SHA1_functions[] = {
...
+    return 0;
+}
+
+static void
+_sha1_free(void *module)
+{
+    _sha1_clear((PyObject *)module);
+}
+
+static int sha1_exec(PyObject *module)
```
Comment (vstinner) [inline Modules/sha1module.c]:
```suggestion
static int
sha1_exec(PyObject *module)
```

For consistency, you may rename it to _sha1_exec(), no?

File: Modules/sha512module.c [hunk 21]
```diff
@@ -422,28 +422,36 @@ sha512_final(unsigned char digest[SHA_DIGESTSIZE], SHAobject *sha_info)
...
  */
 
-static PyTypeObject SHA384type;
-static PyTypeObject SHA512type;
+typedef struct {
+    PyTypeObject* sha384_type;
+    PyTypeObject* sha512_type;
+} SHA512State;
 
+static inline SHA512State* sha512_get_state(PyObject *module)
```
Comment (vstinner) [inline Modules/sha512module.c]:
```suggestion
static inline SHA512State*
sha512_get_state(PyObject *module)
```

File: Modules/sha512module.c [hunk 22]
```diff
@@ -422,28 +422,36 @@ sha512_final(unsigned char digest[SHA_DIGESTSIZE], SHAobject *sha_info)
...
+{
+    void *state = PyModule_GetState(module);
+    assert(state != NULL);
+    return (SHA512State *)state;
+}
 
-static SHAobject *
-newSHA384object(void)
+static SHAobject *newSHA384object(SHA512State *st)
```
Comment (vstinner) [inline Modules/sha512module.c]:
```suggestion
static SHAobject *
newSHA384object(SHA512State *st)
```

File: Modules/sha512module.c [hunk 23]
```diff
@@ -422,28 +422,36 @@ sha512_final(unsigned char digest[SHA_DIGESTSIZE], SHAobject *sha_info)
...
 {
-    return (SHAobject *)PyObject_New(SHAobject, &SHA384type);
+    return (SHAobject *)PyObject_New(SHAobject, st->sha384_type);
 }
 
-static SHAobject *
-newSHA512object(void)
+static SHAobject *newSHA512object(SHA512State *st)
```
Comment (vstinner) [inline Modules/sha512module.c]:
```suggestion
static SHAobject *
newSHA512object(SHA512State *st)
```

File: Modules/sha512module.c [hunk 24]
```diff
@@ -452,20 +460,23 @@ SHA512_dealloc(PyObject *ptr)
...
+SHA512Type_copy_impl(SHAobject *self, PyTypeObject *cls)
+/*[clinic end generated code: output=85ea5b47837a08e6 input=f673a18f66527c90]*/
 {
     SHAobject *newobj;
+    SHA512State *st = PyType_GetModuleState(cls);
 
-    if (Py_IS_TYPE((PyObject*)self, &SHA512type)) {
-        if ( (newobj = newSHA512object())==NULL)
+    if (Py_IS_TYPE((PyObject*)self, st->sha512_type)) {
+        if ( (newobj = newSHA512object(st))==NULL)
```
Comment (vstinner) [inline Modules/sha512module.c]: You can take this PR as an oportunity to add braces to modified if (PEP 7).

File: Modules/sha512module.c [hunk 25]
```diff
@@ -452,20 +460,23 @@ SHA512_dealloc(PyObject *ptr)
...
             return NULL;
     } else {
```
Comment (vstinner) [inline Modules/sha512module.c]: If you modify the if, you can also adapt it to PEP 7 style:

```suggestion
    }
    else {
```

File: Modules/sha512module.c [hunk 26]
```diff
@@ -738,43 +718,79 @@ static struct PyMethodDef SHA_functions[] = {
...
+_sha512_free(void *module)
+{
+    _sha512_clear((PyObject *)module);
+}
 
-PyMODINIT_FUNC
-PyInit__sha512(void)
+
+/* Initialize this module. */
+static int sha512_exec(PyObject *m)
```
Comment (vstinner) [inline Modules/sha512module.c]:
```suggestion
static int
sha512_exec(PyObject *m)
```

Maybe rename to _sha512_exec()?

File: Modules/sha512module.c (hunk 24 above)
Comment (koubaa) [reply Modules/sha512module.c]: @vstinner I like this idea.  In my other projects I am a huge opportunist every time I touch a line of code I clean it up if possible.

File: Modules/md5module.c [hunk 27]
```diff
@@ -349,9 +359,10 @@ static PyObject *
 MD5Type_copy_impl(MD5object *self)
 /*[clinic end generated code: output=596eb36852f02071 input=2c09e6d2493f3079]*/
 {
-    MD5object *newobj;
+    MD5State *st = PyType_GetModuleState(Py_TYPE(self));
```
Comment (vstinner) [inline Modules/md5module.c]: You should use "cls: defining_class" in the clinic input, and use cls rather than Py_TYPE(self).

So you can remove the comment below:

```
// Using PyType_GetModuleState() on this type is safe since
// it cannot be subclassed: it does not have the Py_TPFLAGS_BASETYPE flag.
```

I guess that the two other modules can get a similar change.

Comment (koubaa) [reply Modules/md5module.c]: @vstinner sure but why would I remove the comment.  I would just replace it with PyType_GetModuleState(cls), right?  Isn't the comment still relevant?

Comment (vstinner) [reply Modules/md5module.c]: If you never use `Py_TYPE(self)` but only pass the defining class, subclassing the type is ok and so the comment can be removed.

Comment (vstinner) [reply Modules/md5module.c]: Please remove the comment.

Comment (koubaa) [reply Modules/md5module.c]: @vstinner oh!  I didn't know that.  This means that I could probably continue with some of the other modules with Py_TPFLAGS_BASETYPE!

Comment (vstinner) [reply Modules/md5module.c]: Sadly, argument clinic cannot be used on all slots (tp_xxx functions) yet. So some functions cannot get the defining class.

File: Modules/sha512module.c [hunk 28]
```diff
@@ -452,21 +463,27 @@ SHA512_dealloc(PyObject *ptr)
...
-/*[clinic end generated code: output=adea896ed3164821 input=9f5f31e6c457776a]*/
+SHA512Type_copy_impl(SHAobject *self, PyTypeObject *cls)
+/*[clinic end generated code: output=85ea5b47837a08e6 input=f673a18f66527c90]*/
 {
     SHAobject *newobj;
+    SHA512State *st = PyType_GetModuleState(cls);
 
-    if (Py_IS_TYPE((PyObject*)self, &SHA512type)) {
-        if ( (newobj = newSHA512object())==NULL)
+    if (Py_IS_TYPE((PyObject*)self, st->sha512_type)) {
```
Comment (vstinner) [inline Modules/sha512module.c:478]: Without defining_class, this test was wrong. So thanks for using defining_class :-)

**Review by vstinner — APPROVED** [review]
LGTM. Thanks for the multiple updates. These PR wasn't easy!

File: Misc/NEWS.d/next/Core and Builtins/2020-08-10-16-11-32.bpo-1635741.O0d3ym.rst [hunk 29]
```diff
@@ -0,0 +1,2 @@
+Port the :mod:`sha1`, :mod:`sha512`, and :mod:`md5` extension modules
```
Comment (vstinner) [inline Misc/NEWS.d/next/Core and Builtins/2020-08-10-16-11-32.bpo-1635741.O0d3ym.rst]: Wait, the module names are wrong.

```suggestion
Port the :mod:`_sha1`, :mod:`_sha512`, and :mod:`_md5` extension modules
```

**Review by vstinner — APPROVED** [review]
LGTM, but please fix the NEWS entry.

**Comment by vstinner** [comment]
Merged, thanks.
