### ISSUE TITLE
Bug in 3.14.1 Release: Dataclass triggers exception when init=False and slots=True

### ISSUE THREAD

**Issue by mkrd** [python/cpython#142251]
# Bug report

### Bug description:

Reproducible with:

```python
from dataclasses import dataclass

@dataclass(init=False, slots=True)
class SomeClass:
	test: int
```

Stack trace:
```
Traceback (most recent call last):
  File ".../reproduce_issue.py", line 4, in <module>
    @dataclass(init=False, slots=True)
     ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.14/3.14.1/Frameworks/Python.framework/Versions/3.14/lib/python3.14/dataclasses.py", line 1426, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
                          frozen, match_args, kw_only, slots,
                          weakref_slot)
  File "/opt/homebrew/Cellar/python@3.14/3.14.1/Frameworks/Python.framework/Versions/3.14/lib/python3.14/dataclasses.py", line 1234, in _process_class
    cls = _add_slots(cls, frozen, weakref_slot, fields)
  File "/opt/homebrew/Cellar/python@3.14/3.14.1/Frameworks/Python.framework/Versions/3.14/lib/python3.14/dataclasses.py", line 1401, in _add_slots
    init_annotate = newcls.__init__.__annotate__
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'wrapper_descriptor' object has no attribute '__annotate__'. Did you mean: '__getstate__'?
```

### CPython versions tested on:

3.14

### Operating systems tested on:

macOS

**Comment by StanFromIreland** [comment]
This seems to be a very recent regression, not present in 3.14.0 or 3.13.9.

**Comment by mkrd** [comment]
Yes, I know that it works on 3.14.0. Not really sure, but it might have been introduced in https://github.com/python/cpython/issues/137530

**Comment by cmaloney** [comment]
I think this is a duplicate of gh-142214

**Comment by hugovk** [comment]
Bisects to 12837c63635559873a5abddf511d38456d69617b / https://github.com/python/cpython/pull/137711.

**Comment by hugovk** [comment]
And the fix https://github.com/python/cpython/pull/142223 for https://github.com/python/cpython/issues/142214 fixes this.

Thanks for the report, let's mark as a duplicate.
