### PR TITLE
gh-89419: gdb: fix printing AttributeError in py-locals when no frame is available

### PR DESCRIPTION
**Pull request by eli-schwartz**
```
Unable to read information on python frame
Python Exception <class 'AttributeError'>: 'NoneType' object has no attribute 'co_name'
```

Regression in commit b4903afd4debbbd71dc49a2c8fefa74a3b6c6832. While refactoring the code into a while loop, the previous early return when no frame exists went missing. We have just printed a message that we cannot get information about this, so the frame will be None, and we cannot attempt to use it.

Discovered on python 3.11, in python 3.12a2 this should error out with `.is_shim()` instead of `co_name`.

* Issue: gh-89419

### CODE REVIEW

**Comment by eli-schwartz** [comment]
This will need manual backporting to 3.11 as cherry-picking doesn't apply cleanly. Prepared at 199e6eccc99331d746560ef02a97dab4cd804a0b.

**Review by pablogsal — APPROVED** [review]

File: Misc/NEWS.d/next/Tools-Demos/2022-12-29-19-22-11.bpo-45256.a0ee_H.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix confusing AttributeError in python-gdb.py when py-locals is used without a frame.
```
Comment (pablogsal) [inline Misc/NEWS.d/next/Tools-Demos/2022-12-29-19-22-11.bpo-45256.a0ee_H.rst]:
```suggestion
Fix a bug that caused an :exc:`AttributeError` to be raised in ``python-gdb.py`` when ``py-locals`` is used without a frame.
```

**Review by kumaraditya303 — APPROVED** [review]

**Comment by kumaraditya303** [comment]
@eli-schwartz Go ahead with the backport, thanks.
