### ISSUE TITLE
Empty __module__ attribute for built-in static methods

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#115231]
# Bug report

### Bug description:

An example:
```pycon
>>> bytes.maketrans.__module__ is None
True
```
c.f. pure-python staticmethod:
```pycon
>>> class Spam:
...     @staticmethod
...     def foo():
...         pass
... 
>>> Spam.foo.__module__
'__main__'
```

I'm not sure, maybe this should be treated rather as a feature request.  Docs [says](https://docs.python.org/3.12/reference/datamodel.html#special-writable-attributes) about the attribute value: "The name of the module the function was defined in, or None if unavailable." But clearly, this value *is* available: the ``type_add_method()`` has ``type`` argument and we could query value of its ``__module__`` attribute.

Edit: BTW, same happens for class methods, e.g.:
```pycon
>>> int.from_bytes.__module__ is None
True
```
Probably this should be fixed as well.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-115232

**Comment by serhiy-storchaka** [comment]
Built-in static and class methods has different types than static and class methods in Python classes. This is not a bug.

Static and class methods in Python classes started to inherit function attributes only since 3.10 (bpo-43682/gh-87848). cc @vstinner

**Comment by skirpichev** [comment]
> Static and class methods in Python classes started to inherit function attributes only since 3.10

Hmm, above code snippet works on 3.8+ as well, e.g.:
```pycon
Python 3.9.19+ (heads/3.9:3f5d9d12c7, Aug 29 2024, 13:17:09) 
[GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> class Spam:
...     @staticmethod
...     def foo():
...         pass
... 
>>> Spam.foo.__module__
'__main__'
>>> 
```

**Comment by serhiy-storchaka** [comment]
Static and class methods in Python classes copy attributes from the wrapped methods. But unbound built-in methods do not have the `__module__` attribute, so not copying it is okay. On other hand, bound built-in methods  have `__module__` equal to None:

```pycon
>>> collections.deque.append.__module__
Traceback (most recent call last):
  File "<python-input-15>", line 1, in <module>
    collections.deque.append.__module__
AttributeError: 'method_descriptor' object has no attribute '__module__'. Did you mean: '__reduce__'?
>>> collections.deque().append.__module__ is None
True
```

We should first decide whether we need the `__module__` attribute for regular builtin methods.

**Comment by skirpichev** [comment]
> We should first decide whether we need the __module__ attribute for regular builtin methods.

That should be helpful for introspection.  E.g. now the ``inspect._signature_fromstr()`` resolves ``module_dict`` to empty for e.g. ``bytes.maketrans()`` or ``int.from_bytes()``.  That essentially forbids e.g. using module constants as default values.
