### ISSUE TITLE
Python Variable isnt private

### ISSUE THREAD

**Issue by ghost** [python/cpython#93123]
Hello dear PYTHON developers
i have found python bug probably it's bug
when i create private variable class i can call in the interpreter 
i m show here
>>> class MyClass:
...     __private_var = "it's text very important"
...
>> c = MyClass()
>>> dir(c)
['_MyClass__private_var', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
you can see in list first item and i can call this variable isnt private
>>> c._MyClass__private_var
"it's text very important"
>>>
it's probably bug 

and pyreadline doestn work on python 3.10.xx
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Failed calling sys.__interactivehook__
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site.py", line 446, in register_readline
    import readline
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
Python Build info:Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
My system is Windows 10 X64
Windows-10-10.0.19044-SP0'

**Comment by JelleZijlstra** [comment]
Thanks for your report, but the mangling behavior for private attributes is documented and well-understood; it's not a bug.

If pyreadline doesn't work with 3.10, that should be reported to the pyreadline project, not to CPython.

**Comment by w0nzy** [comment]
thank you best regards
