### ISSUE TITLE
[3.12 Regression] backport of gh-120233 to 3.12 (gh-121350) breaks mercurial, working with 3.12.4

### ISSUE THREAD

**Issue by doko42** [python/cpython#122438]
# Bug report

### Bug description:

mercurial 6.8 fails to start with the 3.12 branch 2024-07-15, but works with 3.12.4:

~$ hg 
 Traceback (most recent call last):
   File "/usr/bin/hg", line 57, in <module>
     from mercurial import dispatch
   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
   File "/usr/lib/python3/dist-packages/hgdemandimport/demandimportpy3.py", line 52, in exec_module
     super().exec_module(module)
   File "<frozen importlib.util>", line 257, in exec_module
   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
   File "/usr/lib/python3/dist-packages/hgdemandimport/demandimportpy3.py", line 52, in exec_module
     super().exec_module(module)
   File "<frozen importlib.util>", line 267, in exec_module
 AttributeError: partially initialized module 'threading' has no attribute 'RLock' (most likely due to a circular import)

Commenting out the hgdemandimport.enable() at line 55 of /usr/bin/hg, it works:

Complete bug report at https://bugs.debian.org/1076449

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by doko42** [comment]
@effigies, is this intended behavior for the 3.12 branch?

**Comment by effigies** [comment]
No. Does hg try to lazily load threading?

**Comment by effigies** [comment]
I think adding `threading` to this list should resolve the issue:

https://foss.heptapod.net/mercurial/mercurial-devel/-/blob/branch/default/hgdemandimport/__init__.py#L22-61

**Comment by doko42** [comment]
please note that you replied to the Debian downstream bug report for mercurial, not upstream mercurial, which would be https://wiki.mercurial-scm.org/BugTracker

**Comment by vstinner** [comment]
I suppose that the commit 94f50f8ee6872007d46c385f7af253497273255a is related to this issue.

**Comment by effigies** [comment]
Yup. I can't reproduce the error in a test, so it's hard to be sure of a python-side fix. Given this can be fixed on the hg end, it's not clear that it's worth further complicating this code.

**Comment by thesamesam** [comment]
Fixed by https://foss.heptapod.net/mercurial/mercurial-devel/-/commit/63ede7a43a3731fecc7e5b535144c6bd59911284.

**Comment by vstinner** [comment]
> Given this can be fixed on the hg end, it's not clear that it's worth further complicating this code.

I suggest to close the issue since it has been fixed in Mercurial.
