### ISSUE TITLE
Calling `help` executes @classmethod @property decorated methods

### ISSUE THREAD

**Issue by a1bae5f9-bb3a-4351-a0ef-d07d0f9f587d** [python/cpython#89519]
BPO | [45356](https://bugs.python.org/issue45356)
--- | :---
Nosy | @rhettinger, @terryjreedy, @ambv, @berkerpeksag, @serhiy-storchaka, @wimglenn, @corona10, @pablogsal, @akulakov, @sirosen, @randolf-scholz, @AlexWaygood
PRs | <li>python/cpython#29239</li>
Files | <li>[classmethod_property.py](https://bugs.python.org/file50325/classmethod_property.py "Uploaded as text/plain at 2021-10-03.19:45:55 by @randolf-scholz")</li><li>[classmethod_property.py](https://bugs.python.org/file50326/classmethod_property.py "Uploaded as text/plain at 2021-10-03.20:21:20 by @randolf-scholz")</li><li>[ClassPropertyIdea.py](https://bugs.python.org/file50344/ClassPropertyIdea.py "Uploaded as text/plain at 2021-10-11.12:55:13 by @randolf-scholz")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = None
created_at = <Date 2021-10-03.19:45:55.963>
labels = ['type-bug', '3.11']
title = 'Calling `help` executes @classmethod @property decorated methods'
updated_at = <Date 2022-02-17.20:03:40.349>
user = 'https://github.com/randolf-scholz'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-17.20:03:40.349>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-10-03.19:45:55.963>
creator = 'randolf.scholz'
dependencies = []
files = ['50325', '50326', '50344']
hgrepos = []
issue_num = 45356
keywords = ['patch']
message_count = 23.0
messages = ['403109', '403110', '403111', '403504', '403505', '403578', '403582', '403611', '403613', '403653', '403699', '403713', '405100', '405115', '405121', '405142', '405143', '406600', '406605', '406606', '407493', '407499', '413451']
nosy_count = 13.0
nosy_names = ['rhettinger', 'terry.reedy', 'grahamd', 'lukasz.langa', 'berker.peksag', 'serhiy.storchaka', 'wim.glenn', 'corona10', 'pablogsal', 'andrei.avk', 'sirosen0', 'randolf.scholz', 'AlexWaygood']
pr_nums = ['29239']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45356'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-110163

**Comment by rhettinger** [comment]
@serhiy-storchaka Do you know if there is a way to add ``PyExc_DeprecationWarning`` directly to the C code without breaking the current code path?  

Here's the relevant code from functionobject.c:

```
static PyObject *
cm_descr_get(PyObject *self, PyObject *obj, PyObject *type)
{
    classmethod *cm = (classmethod *)self;

    if (cm->cm_callable == NULL) {
        PyErr_SetString(PyExc_RuntimeError,
                        "uninitialized classmethod object");
        return NULL;
    }
    if (type == NULL)
        type = (PyObject *)(Py_TYPE(obj));
    if (Py_TYPE(cm->cm_callable)->tp_descr_get != NULL) {
        // FIXME: How to add a PyExc_DeprecationWarning here without breaking code
        return Py_TYPE(cm->cm_callable)->tp_descr_get(cm->cm_callable, type,
                                                      type);
    }
    return PyMethod_New(cm->cm_callable, type);
}

```

Right now, I thinking this has to be a documentation-only deprecation.

**Comment by serhiy-storchaka** [comment]
Seems the problem with the deprecation is that Python functions are descriptors, so in case of normal class methods we pass the same path as for properties. Am I right?

I think that instead of emitting a deprecation warning when read a class property, it should be emitted when the class property is created. We can start with emitting warning if the `classmethod()` argument is a `property` instance. Or if it is a data descriptor (because setting and deleting the class attribute are broken anyway).

**Comment by Paebbels** [comment]
@randolf-scholz I also did experiments on class properties, but with some differences:
* no chaining of `classmethod` and `property`
* my usecase includes getters and **setters**

My observations are:
1. The descriptor protocol implementation is broken on classes. As you already described, setters don't work because `__set__` is not called.
2. By writing to a read-only class property, the descriptor is replaced by a value. This allows code to overwrite internal data's protecting code (getters).

Expectations from user side are:
* Everything in Python are objects of classes. Thus when objects have properties, classes must be able to have them too, because classes have meta classes.
* The descriptor protocol is not limited in any way, so it must work on instances and classes with same behavior.
* Even if the descriptor protocol would be limited to be read-only on classes, then it's shouldn't be allowed to replace a descriptor.


The following code demonstrates how a descriptor is replaced by an integer:

```python
from typing import Callable, Any


def classproperty(method):
	"""A decorator adding properties to classes."""

	class ClassPropertyDescriptor:
		"""A descriptor for class properties.."""

		_name: str
		_getter: Callable
		_setter: Callable
		_deleter: Callable

		def __init__(self, getter: Callable = None, setter: Callable = None, deleter: Callable = None, doc: str = None):
			self._getter = getter
			self._setter = setter
			self._deleter = deleter
			self._name = ''

			if doc is None and getter is not None:
				doc = getter.__doc__
			self.__doc__ = doc

		def __set_name__(self, owner: Any, name: str):
			self._name = name

		def __get__(self, instance: Any, objtype: type = None):
			if self._getter is None:
				raise AttributeError(f'unreadable attribute {self._name}')

			return self #._getter(objtype)

		def __set__(self, instance: Any, value: Any):
			print(f"__set__: {value}")
			if self._setter is None:
				raise AttributeError(f"can't set attribute {self._name}")

			self._setter(instance, value)

		def __delete__(self, instance: Any):
			if self._deleter is None:
				raise AttributeError(f"can't delete attribute {self._name}")

			self._deleter(type(instance))

		def getter(self, getter: Callable):
			prop = type(self)(getter, self._setter, self._deleter, self.__doc__)
			prop._name = self._name

			return prop

		def setter(self, setter: Callable):
			prop = type(self)(self._getter, setter, self._deleter, self.__doc__)
			prop._name = self._name

			print(f"setter: self: {id(self)}; prop:{id(prop)}")
			return prop

		def deleter(self, deleter: Callable):
			prop = type(self)(self._getter, self._setter, deleter, self.__doc__)
			prop._name = self._name

			return prop

	return ClassPropertyDescriptor(method)


class TestClass:
	_member: int = 1

	@classproperty
	def Member(cls) -> int:
		"""Class_1.Member"""
		return cls._member

	@Member.setter
	def Member(cls, value: int) -> None:
		print(f"value: {value} {cls} {id(cls)}")
		cls._member = value


def main():
	print(f"TestClass.Member: {TestClass.Member}   {id(TestClass.Member)}")

	TestClass.Member.__set__(TestClass, 12)
	TestClass.Member = 13
	TestClass.Member.__set__(TestClass, 14)
	print(f"TestClass.Member: {TestClass.Member}   {id(TestClass.Member)}")


if __name__ == "__main__":
	main()
```

Output:
```
setter: self: 1674684726480; prop:1674684726384
TestClass.Member: <__main__.classproperty.<locals>.ClassPropertyDescriptor object at 0x00000185EAFCFC70>   1674684726384
__set__: 12
value: 12 <class '__main__.TestClass'> 1674666598048
```

Error message:
```
AttributeError: 'int' object has no attribute '__set__'. Did you mean: '__eq__'?
```

By changing how the descriptor works for `__get__`, the descriptor itself can be exposed and `__set__` can be called manually. In the first case, the value `12` can be set. Then `13` is assigned which replaces the descriptor. Now setting `14` causes an exception because the descriptor was replaced.

------
Tested with Python 3.10.

**Comment by zduvall** [comment]
> In Python 3.10, classmethod() added a __wrapped__ attribute. Presumably, any use case for implicit chaining can now be accomplished in an explicit and controlled manner.

@rhettinger - Could you share an example of how you would do this as a replacement for chaining `@classmethod` and `@property`?

**Comment by KevinMGranger** [comment]
It's really disappointing that this behavior would be changed without the standard deprecation cycle. Surely there should be an alternative introduced so people have time to transition?

**Comment by MattF-NSIDC** [comment]
Wrapping `abstractmethod` with `classmethod` is still documented as a valid approach in 3.11 docs: https://docs.python.org/3.11/library/abc.html#abc.abstractclassmethod , but the [classmethod docs](https://docs.python.org/3.11/library/functions.html#classmethod) indicate this wouldn't work. How should I write code that won't break under 3.11 here?

Since `classmethod` docs indicate the wrapping functionality will be _disabled_ in 3.11, it sounds like `@abstractclassmethod` is the way to go -- it may be deprecated as of 3.10, but I don't see any suggestion it will be removed in 3.11, and I don't see an alternative.

**Comment by Prometheus3375** [comment]
@KevinMGranger @MattF-NSIDC classmethod docs says that `classmethod` cannot wrap other *descriptors*. You can still apply decorators to a function and then wrap it with `classmethod`. In other words, you can use as many decorators before `classmethod` as you want while all of them does return non-descriptor objects.

`abstractmethod` does not return a descriptor, so its chaining with `classmethod` works in 3.11. In fact, `abstractmethod` just adds an attribute to passed function and then returns it.

```python
def abstractmethod(funcobj):
    """A decorator indicating abstract methods.

    Requires that the metaclass is ABCMeta or derived from it.  A
    class that has a metaclass derived from ABCMeta cannot be
    instantiated unless all of its abstract methods are overridden.
    The abstract methods can be called using any of the normal
    'super' call mechanisms.  abstractmethod() may be used to declare
    abstract methods for properties and descriptors.

    Usage:

        class C(metaclass=ABCMeta):
            @abstractmethod
            def my_abstract_method(self, ...):
                ...
    """
    funcobj.__isabstractmethod__ = True
    return funcobj
```

**Comment by SimpleArt** [comment]
> > In Python 3.10, classmethod() added a **wrapped** attribute. Presumably, any use case for implicit chaining can now be accomplished in an explicit and controlled manner.
> 
> @rhettinger - Could you share an example of how you would do this as a replacement for chaining `@classmethod` and `@property`?

@zduvall Here is an implementation for a read-only class property that is backwards/forwards compatible:

```python
import sys
from typing import Generic, Optional, TypeVar

if sys.version_info < (3, 9):
    from typing import Callable, Type
else:
    from builtins import type as Type
    from collections.abc import Callable

T = TypeVar("T")
RT = TypeVar("RT")


class classproperty(Generic[T, RT]):
    """
    Class property attribute (read-only).

    Same usage as @property, but taking the class as the first argument.

        class C:
            @classproperty
            def x(cls):
                return 0

        print(C.x)    # 0
        print(C().x)  # 0
    """

    def __init__(self, func: Callable[[Type[T]], RT]) -> None:
        # For using `help(...)` on instances in Python >= 3.9.
        self.__doc__ = func.__doc__
        self.__module__ = func.__module__
        self.__name__ = func.__name__
        self.__qualname__ = func.__qualname__
        # Consistent use of __wrapped__ for wrapping functions.
        self.__wrapped__: Callable[[Type[T]], RT] = func

    def __set_name__(self, owner: Type[T], name: str) -> None:
        # Update based on class context.
        self.__module__ = owner.__module__
        self.__name__ = name
        self.__qualname__ = owner.__qualname__ + "." + name

    def __get__(self, instance: Optional[T], owner: Optional[Type[T]] = None) -> RT:
        if owner is None:
            owner = type(instance)
        return self.__wrapped__(owner)
```

Additionally, as shown in this issue thread, running `help(...)` on things like this will not work as expected. In the example shown in `help(classproperty)`, running `help(C)` will show `x = 0` instead of the documentation for the class property, if any. This is the same behavior as the current `@classmethod @property` solution, nothing fancy there. As such, you may want to simplify the `__init__` and remove the `__set_name__` as being completely unnecessary.

Note also that as shown by @Paebbels, the descriptor protocol ONLY supports class getters, it does not support class setters or class deleters. As such, only read-only class properties are possible.

This isn't to say you can't have mutable class properties however, only that you can't have them follow the descriptor protocol for the nicer syntax. You can instead have the class getter return objects with `.get`, `.set`, and `.delete` methods as a workaround:

```python
import sys
from types import MethodType
from typing import Any, Callable, Generic, Optional, TypeVar, Union

if sys.version_info < (3, 9):
    from typing import Type
else:
    from builtins import type as Type

if sys.version_info < (3, 11):
    Self = TypeVar("Self", bound="classproperty")
else:
    from typing import Self

T = TypeVar("T")


class BoundClassDescriptor(Generic[T]):

    def __init__(
        self,
        owner: Type[T],
        descriptor: property,
        module: Optional[str],
        name: Optional[str],
        qualname: Optional[str],
    ) -> None:
        self.__doc__ = descriptor.__doc__
        self.__module__ = module
        self.__name__ = name
        self.__qualname__ = qualname
        self.__wrapped__: property = descriptor

        self.get: Callable[[], Any]
        self.set: Callable[[Any], object]
        self.delete: Callable[[], object]

        if descriptor.fget is not None:
            self.get = MethodType(descriptor.fget, owner)

        if descriptor.fset is not None:
            self.set = MethodType(descriptor.fset, owner)

        if descriptor.fdel is not None:
            self.delete = MethodType(descriptor.fdel, owner)


class classproperty(Generic[T]):

    def __init__(
        self,
        fget: Optional[Callable[[Type[T]], Any]] = None,
        fset: Optional[Callable[[Type[T], Any], object]] = None,
        fdel: Optional[Callable[[Type[T]], object]] = None,
        doc: Optional[str] = None,
    ) -> None:
        self.__module__ = None
        self.__name__ = None
        self.__qualname__ = None
        self.__wrapped__: property = property(fget, fset, fdel, doc)

    def __set_name__(self, owner: Type[T], name: str) -> None:
        self.__module__ = owner.__module__
        self.__name__ = name
        self.__qualname__ = owner.__qualname__ + "." + name

    def __get__(
        self, instance: Optional[T], owner: Optional[Type[T]] = None
    ) -> BoundClassDescriptor[T]:
        if owner is None:
            owner = type(instance)
        return BoundClassDescriptor(
            owner,
            self.__wrapped__,
            self.__module__,
            self.__name__,
            self.__qualname__,
        )

    def getter(self: Self, func: Callable[[Type[T]], Any]) -> Self:
        self.__wrapped__ = self.__wrapped__.getter(func)
        return self

    def setter(self: Self, func: Callable[[Type[T], Any], object]) -> Self:
        self.__wrapped__ = self.__wrapped__.setter(func)
        return self

    def deleter(self: Self, func: Callable[[Type[T]], object]) -> Self:
        self.__wrapped__ = self.__wrapped__.deleter(func)
        return self
```

Example:

```python
class A:
    _foo = 0

    @classproperty
    def foo(cls):
        """Description of foo class property."""
        return cls._foo

    @foo.setter
    def foo(cls, value):
        cls._foo = value


class B(A):
    pass
```

Usage:

```python
>>> # Getters/setters/deleters work as you'd expect using `A._foo` directly.
>>> A.foo.get()
0
>>> B.foo.get()
0
>>> 
>>> A.foo.set(1)
>>> A.foo.get()
1
>>> B.foo.get()
1
>>> 
>>> B.foo.set(2)
>>> A.foo.get()
1
>>> B.foo.get()
2
>>> 
>>> help(A.foo)  # Instance documentation works in Python >= 3.9.
Help on BoundClassDescriptor in A:

A.foo = <BoundClassDescriptor object>
    Description of foo class property.

>>> help(A.foo.get)
Help on method foo in module __main__:

foo() method of builtins.type instance
    Description of foo class property.

>>> help(A.foo.set)  # You could have custom setter documentation.
Help on method foo in module __main__:

foo(value) method of builtins.type instance

>>> help(A.foo.delete)  # Only has a delete method if one was set.
Traceback (most recent call last):
  ...
AttributeError: 'BoundClassDescriptor' object has no attribute 'delete'
```

Of course the documentation won't work on static analyzers, but you'll at least be able to dynamically use `help(...)` and get what you'd expect.

**Comment by SimpleArt** [comment]
One minor detail concerning abstract properties is that removing `classmethod` chaining no longer allows one to use abstract class properties:

```python
from abc import ABC, abstractmethod


class C(ABC):

    @property
    @classmethod
    @abstractmethod
    def expensive_class_property(cls):
        ...
```

I don't think anyone's going to miss this though, and if you're going so far then the workaround is to use `typing.Protocol` instead with `expensive_class_property: classproperty` from one of the above implementations, along with mixin classes instead of the abstract class.

**Comment by Paebbels** [comment]
> Note also that as shown by @Paebbels, the descriptor protocol ONLY supports class getters, it does not support class setters or class deleters. As such, only read-only class properties are possible.

@SimpleArt  
This statement is not fully correct. A read-only property prevents write access. The current implementation of Python doesn't do this, so third parties can "destroy" a descriptor for the class property getter.

Thus:
1. Python has a bug
2. Has a vulnerability problem
3. Python is inconsistent, because the descriptor protocol is not a generic implementation working on any object. Also types (classes) are objects.

------
/cc @skoehler

**Comment by SimpleArt** [comment]
@Paebbels To clarify, the inconsistency is assuming "read-only property" translates to "read-only class property" or "read-only descriptor". There's simply no such thing as an actual "read-only" thing, all a read-only property does is define a `__set__` that raises an error *when accessed on an instance*.

Quite frankly, changing it so that `__set__` is called when a descriptor is accessed on the class itself just sounds more trouble than it's worth because it makes meta usage more confusing and introduce more potential bugs. That is to say, there are cases where one may need to apply changes to a class after its creation, like with class decorators.

**Comment by SimpleArt** [comment]
> > In Python 3.10, classmethod() added a **wrapped** attribute. Presumably, any use case for implicit chaining can now be accomplished in an explicit and controlled manner.
> 
> @rhettinger - Could you share an example of how you would do this as a replacement for chaining `@classmethod` and `@property`?

After writing the previous comment, I realized that there's a much simpler alternative that avoids all of the complicated code. Metaclasses.

```python
class MetaC(type):

    @property
    def expensive_class_property(self):
        ...


class C(metaclass=MetaC):
    pass
```

Unlike properties which are defined within `C`, you cannot use `C().expensive_class_property`. This will however allow you to create setters on classes which "actually work" e.g. you can use `C.expensive_class_property += 1`.

Just be wary of metaclass conflicts.

**Comment by SimpleArt** [comment]
I can't help but wonder, not being very familiar with the C side of things here to know how `help` is implemented, since when and why did using `help(...)` ever try to run descriptors at all, and if not if that could be changed.

Indeed this original problem is not necessarily the fault of `classmethod` and fails on ANY descriptor:

```python
class Descriptor:
    """Description of this descriptor."""

    def __get__(self, instance, owner=None):
        print("expensive descriptor getter")


class Foo:
    foo = Descriptor()
```

Running `help(Foo)` produces the following:

```
expensive descriptor getter
expensive descriptor getter
expensive descriptor getter
expensive descriptor getter
Help ...
```

I assume the fact that the getter is ran 4 times instead of once is definitely a bug that is getting fixed. I also assume the point of running the getter is so that the help documentation can display the value, as it does at runtime:

```
Help on class Foo in module __main__:

class Foo(builtins.object)
 |  Methods defined here:
 |
 |  foo = None
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
```

However, compare the documentation to that of `@property`:

```python
>>> class Bar:
...     @property
...     def foo():
...         """Description of this property."""
... 
>>> help(Bar)
Help on class Bar in module __main__:

class Bar(builtins.object)
 |  Readonly properties defined here:
 |
 |  foo
 |      Description of this property.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
```

From the documentation specifically, the way I see it is that there are two differences:

- Properties are correctly placed under `Readonly properties defined here:`, while descriptors are misplaced under `Methods defined here:`.
- Properties (not class properties) display their documentation and do not compute their value, while descriptors compute their value and display only it. Even with `return object_with_doc` for the descriptor, no documentation is shown.

Personally, I don't find displaying the value very useful. At the point that it's something like a descriptor, *there's a reason it's not just a value*. It may not be the same value every time or I may not want to calculate it if I don't have to. My expectation is that using `help(Foo)` should show up something like this:

```
Help on class Foo in module __main__:

class Foo(builtins.object)
 |  Descriptors defined here:
 |
 |  foo = <__main__.Descriptor object at ...>
 |      Description of this descriptor.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
```

This approach would also let one display a value if they want by implementing `Descriptor.__repr__`, so maybe it would show something like this:

```
Help on class Foo in module __main__:

class Foo(builtins.object)
 |  Descriptors defined here:
 |
 |  cached_foo = Descriptor(value=3)
 |      Description of this descriptor.
 |
 |  uncached_foo = Descriptor()
 |      Description of this descriptor.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
```

**Comment by SimpleArt** [comment]
Concerning the chaining of `@property` and `@classmethod`, I did notice that there is potential to have both in a way which does not cause significant confusion by introducing a `cget` value which should roughly look like this:

```python
class property:

    def __init__(self, fget=None, fset=None, fdel=None, doc=None, cget=None):
        if doc is None and fget is not None:
            doc = fget.__doc__
        if isinstance(fget, classmethod):
            if cget is not None:
                raise TypeError("got class getter with classmethod fget")
            cget = fget
            fget = None
        self.fget = fget
        self.fset = fset
        self.fdel = fdel
        self.__doc__ = doc
        self.cget = cget

    def __get__(self, instance, owner=None):
        if instance is None:
            return self.cget(owner)
        elif self.cget is None:  # The default behavior is to return the property object.
            return self
        else:
            return self.fget(owner)

    def getter(self, fget):
        if isinstance(fget, classmethod):
            return property(self.fget, self.fset, self.fdel, self.__doc__, fget)
        else:
            return property(fget, self.fset, self.fdel, self.__doc__, self.cget)
```

Example usage:

```python
class C:

    @property
    @classmethod
    def is_instance(cls) -> bool:
        return False

    @is_instance.getter
    def is_instance(self) -> bool:
        return True


print(C.is_instance)    # False
print(C().is_instance)  # True
```

Although I can't imagine a case where you'd want to use both, this would definitely let you consistently use each approach individually. The drawback that I see from this however is the fact that people might get confused and think that you can use `@property.setter` with `@classmethod`. An error could get raised at this point, but people might try to remove the `@classmethod` to avoid the error. I think that linters should then complain that the setter should take `self` instead of `cls`, really cementing the fact that a writable class property shouldn't work. Take it as you will.

**Comment by sobolevn** [comment]
Now 3.13 is in the works, so this can be changed according to the TODO item in `3.11.rst`:

```
Pending Removal in Python 3.13
------------------------------

* :class:`classmethod` descriptor chaining (:gh:`89519`)
```

**Comment by Prometheus3375** [comment]
[Here](https://github.com/python/cpython/issues/89519#issuecomment-1397534245) is the sample of the implementation. You can also use a metaclass to add a property.

**Comment by ReHoss** [comment]
> > > In Python 3.10, classmethod() added a **wrapped** attribute. Presumably, any use case for implicit chaining can now be accomplished in an explicit and controlled manner.
> > 
> > 
> > @rhettinger - Could you share an example of how you would do this as a replacement for chaining `@classmethod` and `@property`?
> 
> @zduvall Here is an implementation for a read-only class property that is backwards/forwards compatible:
> 
> ```python
> import sys
> from typing import Generic, Optional, TypeVar
> 
> if sys.version_info < (3, 9):
>     from typing import Callable, Type
> else:
>     from builtins import type as Type
>     from collections.abc import Callable
> 
> T = TypeVar("T")
> RT = TypeVar("RT")
> 
> 
> class classproperty(Generic[T, RT]):
>     """
>     Class property attribute (read-only).
> 
>     Same usage as @property, but taking the class as the first argument.
> 
>         class C:
>             @classproperty
>             def x(cls):
>                 return 0
> 
>         print(C.x)    # 0
>         print(C().x)  # 0
>     """
> 
>     def __init__(self, func: Callable[[Type[T]], RT]) -> None:
>         # For using `help(...)` on instances in Python >= 3.9.
>         self.__doc__ = func.__doc__
>         self.__module__ = func.__module__
>         self.__name__ = func.__name__
>         self.__qualname__ = func.__qualname__
>         # Consistent use of __wrapped__ for wrapping functions.
>         self.__wrapped__: Callable[[Type[T]], RT] = func
> 
>     def __set_name__(self, owner: Type[T], name: str) -> None:
>         # Update based on class context.
>         self.__module__ = owner.__module__
>         self.__name__ = name
>         self.__qualname__ = owner.__qualname__ + "." + name
> 
>     def __get__(self, instance: Optional[T], owner: Optional[Type[T]] = None) -> RT:
>         if owner is None:
>             owner = type(instance)
>         return self.__wrapped__(owner)
> ```
> 
> Additionally, as shown in this issue thread, running `help(...)` on things like this will not work as expected. In the example shown in `help(classproperty)`, running `help(C)` will show `x = 0` instead of the documentation for the class property, if any. This is the same behavior as the current `@classmethod @property` solution, nothing fancy there. As such, you may want to simplify the `__init__` and remove the `__set_name__` as being completely unnecessary.
> 
> Note also that as shown by @Paebbels, the descriptor protocol ONLY supports class getters, it does not support class setters or class deleters. As such, only read-only class properties are possible.
> 
> This isn't to say you can't have mutable class properties however, only that you can't have them follow the descriptor protocol for the nicer syntax. You can instead have the class getter return objects with `.get`, `.set`, and `.delete` methods as a workaround:
> 
> ```python
> import sys
> from types import MethodType
> from typing import Any, Callable, Generic, Optional, TypeVar, Union
> 
> if sys.version_info < (3, 9):
>     from typing import Type
> else:
>     from builtins import type as Type
> 
> if sys.version_info < (3, 11):
>     Self = TypeVar("Self", bound="classproperty")
> else:
>     from typing import Self
> 
> T = TypeVar("T")
> 
> 
> class BoundClassDescriptor(Generic[T]):
> 
>     def __init__(
>         self,
>         owner: Type[T],
>         descriptor: property,
>         module: Optional[str],
>         name: Optional[str],
>         qualname: Optional[str],
>     ) -> None:
>         self.__doc__ = descriptor.__doc__
>         self.__module__ = module
>         self.__name__ = name
>         self.__qualname__ = qualname
>         self.__wrapped__: property = descriptor
> 
>         self.get: Callable[[], Any]
>         self.set: Callable[[Any], object]
>         self.delete: Callable[[], object]
> 
>         if descriptor.fget is not None:
>             self.get = MethodType(descriptor.fget, owner)
> 
>         if descriptor.fset is not None:
>             self.set = MethodType(descriptor.fset, owner)
> 
>         if descriptor.fdel is not None:
>             self.delete = MethodType(descriptor.fdel, owner)
> 
> 
> class classproperty(Generic[T]):
> 
>     def __init__(
>         self,
>         fget: Optional[Callable[[Type[T]], Any]] = None,
>         fset: Optional[Callable[[Type[T], Any], object]] = None,
>         fdel: Optional[Callable[[Type[T]], object]] = None,
>         doc: Optional[str] = None,
>     ) -> None:
>         self.__module__ = None
>         self.__name__ = None
>         self.__qualname__ = None
>         self.__wrapped__: property = property(fget, fset, fdel, doc)
> 
>     def __set_name__(self, owner: Type[T], name: str) -> None:
>         self.__module__ = owner.__module__
>         self.__name__ = name
>         self.__qualname__ = owner.__qualname__ + "." + name
> 
>     def __get__(
>         self, instance: Optional[T], owner: Optional[Type[T]] = None
>     ) -> BoundClassDescriptor[T]:
>         if owner is None:
>             owner = type(instance)
>         return BoundClassDescriptor(
>             owner,
>             self.__wrapped__,
>             self.__module__,
>             self.__name__,
>             self.__qualname__,
>         )
> 
>     def getter(self: Self, func: Callable[[Type[T]], Any]) -> Self:
>         self.__wrapped__ = self.__wrapped__.getter(func)
>         return self
> 
>     def setter(self: Self, func: Callable[[Type[T], Any], object]) -> Self:
>         self.__wrapped__ = self.__wrapped__.setter(func)
>         return self
> 
>     def deleter(self: Self, func: Callable[[Type[T]], object]) -> Self:
>         self.__wrapped__ = self.__wrapped__.deleter(func)
>         return self
> ```
> 
> Example:
> 
> ```python
> class A:
>     _foo = 0
> 
>     @classproperty
>     def foo(cls):
>         """Description of foo class property."""
>         return cls._foo
> 
>     @foo.setter
>     def foo(cls, value):
>         cls._foo = value
> 
> 
> class B(A):
>     pass
> ```
> 
> Usage:
> 
> ```python
> >>> # Getters/setters/deleters work as you'd expect using `A._foo` directly.
> >>> A.foo.get()
> 0
> >>> B.foo.get()
> 0
> >>> 
> >>> A.foo.set(1)
> >>> A.foo.get()
> 1
> >>> B.foo.get()
> 1
> >>> 
> >>> B.foo.set(2)
> >>> A.foo.get()
> 1
> >>> B.foo.get()
> 2
> >>> 
> >>> help(A.foo)  # Instance documentation works in Python >= 3.9.
> Help on BoundClassDescriptor in A:
> 
> A.foo = <BoundClassDescriptor object>
>     Description of foo class property.
> 
> >>> help(A.foo.get)
> Help on method foo in module __main__:
> 
> foo() method of builtins.type instance
>     Description of foo class property.
> 
> >>> help(A.foo.set)  # You could have custom setter documentation.
> Help on method foo in module __main__:
> 
> foo(value) method of builtins.type instance
> 
> >>> help(A.foo.delete)  # Only has a delete method if one was set.
> Traceback (most recent call last):
>   ...
> AttributeError: 'BoundClassDescriptor' object has no attribute 'delete'
> ```
> 
> Of course the documentation won't work on static analyzers, but you'll at least be able to dynamically use `help(...)` and get what you'd expect.

Hi @SimpleArt ,

The `pyright` type checker for the instruction `return self.__wrapped__(owner)` returns: 


_Argument of type &quot;type[T@classproperty] | type[object]* | None; cannot be assigned to parameter of type ";type[T@classproperty]";<br/>&nbsp;&nbsp;Type ";type[T@classproperty] | type[object]* | None"; is incompatible with type ";type[T@classproperty]"; (reportArgumentType)_

for this slightly modified version of the `__get__` method (modified such that `type(None)` does not happen)

```python
    def __get__(self, instance: Optional[T], owner: Type[T] | None = None) -> RT:
        if owner is None:
            if instance is not None:
                owner = type(instance)
            else:
                owner = None
        return self.__wrapped__(owner)  # pyright triggers warning
```

also this assignment 

```python
        self.__module__ = func.__module__
```

gives

_Cannot find reference '__module__' in '(T) -> RT'_

**Comment by STofone** [comment]
`classproperty` breaks the type checker.
While Metaclass cannot be generic.
Makes this code impossible to work fine
```python
from typing import Callable


class META_A[T](type):
    @property
    def set_func_for_t(cls):
        def set_func(func: Callable[[T]]):
            pass

        return set_func


class A[T](metaclass=META_A[T]):
    pass
```
