### ISSUE TITLE
Configure option --with-cxx-main=/usr/bin/clang++ not working

### ISSUE THREAD

**Issue by MaxwellDupre** [python/cpython#93744]
**Configure option --with-cxx-main=/usr/bin/clang++ not working**

**My environment**

- CPython versions tested on: 
Latest 3.12.0.a0 tried on other but CC=/usr/bin/clang not working on those, so pointless to try
- Operating system and architecture:
fedora 5.17.13-300.fc36.x86_64

Configure options 
--with-cxx-main=/usr/bin/clang++ CC=/usr/bin/clang
 runs and gives at end:
`configure: creating Modules/Setup.local`
`configure: creating Makefile`
`configure:`

Then:
`make`
/usr/bin/clang++ -c -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall    -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include    -DPy_BUILD_CORE -o Programs/python.o ./Programs/python.c
clang-14: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
error: invalid argument '-std=c11' not allowed with 'C++'
make: *** [Makefile:1373: Programs/python.o] Error 1

See [Discuss](https://discuss.python.org/t/compiling-python-with-clang/16323/4) report

Tried configure with --with-cxx-main=/usr/bin/g++ CC=/usr/bin/gcc
then
`make`
cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++
cc1plus: warning: command-line option ‘-std=c11’ is valid for C/ObjC but not for C++

Shows source files being compiled and linked and actually builds python executable, so this **works**.

**Comment by kumaraditya303** [comment]
If you do `CC=clang ./configure` it works fine. This is not a Python bug, you can ask this on discourse Users category.

**Comment by erlend-aasland** [comment]
> This is a bug: explain why its not!

Please remain calm and use a polite tone.

> I have raised a question on discourse and it was not answered!

25 minutes ago. There is no guarenteed response time; we are all volunteers, trying to improve CPython in our free time. Once again, please use a polite tone.

**Comment by kumaraditya303** [comment]
The discuss report [^1] you linked has been answered by a core dev and the author claimed that by syncing with 3.12 it works and then you are saying that it has not been answered. Please remain calmso that our autoconf experts will take a look. Thanks



[^1]:https://discuss.python.org/t/compiling-python-with-clang/16323/4

**Comment by tiran** [comment]
GCC's C++ compiler just warns about `-stdc=c11` option. Do we support building with Clang's C++ compiler?
```
g++ -c -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall    -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden  -I../../Include/internal -IObjects -IInclude -IPython -I. -I../../Include    -DPy_BUILD_CORE -o Programs/python.o ../../Programs/python.c
cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++
cc1plus: warning: command-line option ‘-std=c11’ is valid for C/ObjC but not for C++
```

**Comment by erlend-aasland** [comment]
> Do we support building with Clang's C++ compiler?

AFAICS, no C++ is mentioned in PEP 11. However, @vstinner has recently pushed a lot of changes to make the code base friendlier to C++ compilers.

**Comment by encukou** [comment]
AFAIK Victor's work is on *public headers*, not Python itself. While you can use the C-API with C++, Python itself is written in C.

Supporting ./configure with C++ seems rather pointless to me, is there a use case where you can't use the C compiler?

**Comment by erlend-aasland** [comment]
> AFAIK Victor's work is on public headers, not Python itself [...]

Yes, correct. That's a related issue, but not directly relevant for this issue.

**Comment by erlend-aasland** [comment]
See also: https://docs.python.org/3/using/configure.html

**Comment by tiran** [comment]
``--with-cxx-main`` is an feature that was introduced in 9501219303c6 (1999). Is still useful?

**Comment by erlend-aasland** [comment]
Here's my 2 cents:

PEP 11 does not say anything about C++ compilers. The current option is broken with at least one C++ compiler.
I say we drop it.

**Comment by encukou** [comment]
I guess the use case might have been ensuring that we can use a C++ compiler/linker with libpython? `testcppext` does that now.

Anyway, if we do drop it, 3.12a0 is the perfect time.

**Comment by vstinner** [comment]
> PEP 11 does not say anything about C++ compilers.

It would be nice to update PEP 11 to require the Python C API to be usable in C++, at least with C++11.

Since Python 3.11, compatibility with C++11 is now **tested**. I recently added a test on C++03.

**Comment by vstinner** [comment]
On Fedora 36, I failed to build Python **3.10** with ``./configure --with-cxx-main=g++ CC=gcc``. g++ fails to build ``Programs/_testembed.c``.

So I don't think that this issue is about fixing Python. It's like a "new feature". IMO ``configure --with-cxx-main=...`` option was broken for many years.

Examples of g++ errors:

Include/internal/pycore_atomic.h is incompatible C++:

```
./Include/internal/pycore_atomic.h:38:32: error: 'memory_order_relaxed' was not declared in this scope
   38 |     _Py_memory_order_relaxed = memory_order_relaxed,
```

putenv() error:

```
./Programs/_testembed.c:168:12: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  168 |     putenv("PYTHONMALLOC=");
```

Many errors related to Py_BUILD_ASSERT_EXPR() used by Py_ARRAY_LENGTH():

```
In file included from ./Include/Python.h:51,
                 from ./Programs/_testembed.c:8:
./Include/pymacro.h:61:30: error: '__builtin_types_compatible_p' was not declared in this scope
   61 |      + Py_BUILD_ASSERT_EXPR(!__builtin_types_compatible_p(typeof(array), \
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
./Include/pymacro.h:40:27: note: in definition of macro 'Py_BUILD_ASSERT_EXPR'
   40 |     (sizeof(char [1 - 2*!(cond)]) - 1)
      |                           ^~~~
./Programs/_testembed.c:319:13: note: in expansion of macro 'Py_ARRAY_LENGTH'
  319 |     Py_Main(Py_ARRAY_LENGTH(argv), argv);
      |             ^~~~~~~~~~~~~~~
./Include/pymacro.h:40:13: error: expected primary-expression before 'char'
   40 |     (sizeof(char [1 - 2*!(cond)]) - 1)
      |             ^~~~
./Include/pymacro.h:61:8: note: in expansion of macro 'Py_BUILD_ASSERT_EXPR'
   61 |      + Py_BUILD_ASSERT_EXPR(!__builtin_types_compatible_p(typeof(array), \
      |        ^~~~~~~~~~~~~~~~~~~~
./Programs/_testembed.c:319:13: note: in expansion of macro 'Py_ARRAY_LENGTH'
  319 |     Py_Main(Py_ARRAY_LENGTH(argv), argv);
      |             ^~~~~~~~~~~~~~~
./Include/pymacro.h:40:13: error: expected ')' before 'char'
   40 |     (sizeof(char [1 - 2*!(cond)]) - 1)
      |            ~^~~~
./Include/pymacro.h:61:8: note: in expansion of macro 'Py_BUILD_ASSERT_EXPR'
   61 |      + Py_BUILD_ASSERT_EXPR(!__builtin_types_compatible_p(typeof(array), \
      |        ^~~~~~~~~~~~~~~~~~~~
./Programs/_testembed.c:319:13: note: in expansion of macro 'Py_ARRAY_LENGTH'
  319 |     Py_Main(Py_ARRAY_LENGTH(argv), argv);
      |             ^~~~~~~~~~~~~~~
./Programs/_testembed.c:319:41: error: expected ')' before ';' token
  319 |     Py_Main(Py_ARRAY_LENGTH(argv), argv);
      |                                         ^
      |                                         )
./Include/pymacro.h:40:5: note: to match this '('
   40 |     (sizeof(char [1 - 2*!(cond)]) - 1)
      |     ^
./Include/pymacro.h:61:8: note: in expansion of macro 'Py_BUILD_ASSERT_EXPR'
   61 |      + Py_BUILD_ASSERT_EXPR(!__builtin_types_compatible_p(typeof(array), \
      |        ^~~~~~~~~~~~~~~~~~~~
./Programs/_testembed.c:319:13: note: in expansion of macro 'Py_ARRAY_LENGTH'
  319 |     Py_Main(Py_ARRAY_LENGTH(argv), argv);
      |             ^~~~~~~~~~~~~~~
./Programs/_testembed.c:319:41: error: expected ')' before ';' token
  319 |     Py_Main(Py_ARRAY_LENGTH(argv), argv);
      |                                         ^
      |                                         )
./Include/pymacro.h:60:5: note: to match this '('
   60 |     (sizeof(array) / sizeof((array)[0]) \
      |     ^
./Programs/_testembed.c:319:13: note: in expansion of macro 'Py_ARRAY_LENGTH'
  319 |     Py_Main(Py_ARRAY_LENGTH(argv), argv);
      |             ^~~~~~~~~~~~~~~
```

**Comment by vstinner** [comment]
I wrote a large PR removing more than just ``--with-cxx-main``: PR #94063.

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/398ed84dc40abc58e16f5014d44c08f20cb4b5f6 which removes the configure option.

It's easy to embed Python in a C++ application: https://docs.python.org/dev/extending/embedding.html
