### PR TITLE
bpo-37878: PyThreadState_DeleteCurrent() was not removed

### PR DESCRIPTION
**Pull request by vstinner**
Update What's New in Python 3.9.

https://bugs.python.org/issue37878

### CODE REVIEW

**Comment by vstinner** [comment]
Issue reported at https://github.com/python/cpython/pull/15315#issuecomment-635067958

**Review by corona10 — APPROVED** [review]
lgtm

**Comment by henryiii** [comment]
Should you mention that it has been moved? There is a section below about changes to the limited ABI that it might fit in. If PyBind11 is the only user, though, we already know that. :)

**Review by henryiii — APPROVED** [review]
Looks great to me! Thanks!

**Comment by vstinner** [comment]
> Should you mention that it has been moved? There is a section below about changes to the limited ABI that it might fit in.

Done.

>  If PyBind11 is the only user, though, we already know that. :)

I don't understand why you mention PyBind11 here. In https://github.com/python/cpython/pull/15315#issuecomment-635067958 you wrote that PyBind11 does not use the limited C API. So PyBind11 is not impactd by https://bugs.python.org/issue37878 changes, right?

You also wrote "Now that 3.9b1 is out, PyBind11-based libraries cannot build" but you didn't explain what is your error.

I don't understand what are you expecting? Do you want to move back the function to the limited C API? Does Pybind11 use the limited C API or not? It's unclear.

**Comment by henryiii** [comment]
It needs to make sure it includes the correct header since this has moved, but otherwise, it does not need to change. PyBind11 does not use the limited API.

There is currently a different issue as well, but I think I was only tripping up on a deprecated warning and falling to compile because I had warnings as errors. I'm setting up a PyBind11 CI build on Python 3.9 and so far it looks promising. I don't think there's an issue from the Python side.

Thanks!

**Comment by vstinner** [comment]
> It needs to make sure it includes the correct header 

Include/cpython/pystate.h is included automatically by Include/pystate.h and cannot be included directly (it fails with a compilation error).
