### PR TITLE
gh-142440: apply context to x, not v, in _decimal_Context_apply_impl

### PR DESCRIPTION
**Pull request by AZero13**
V is not even defined here.

* Issue: gh-142440

### CODE REVIEW

**Review by skirpichev — APPROVED** [review]
Thanks, that's a typo, introduced by ef4dd1d65520.

File: Misc/NEWS.d/next/Library/2025-12-08-18-40-17.gh-issue-142438.tH-Y16.rst
Comment (StanFromIreland) [inline Misc/NEWS.d/next/Library/2025-12-08-18-40-17.gh-issue-142438.tH-Y16.rst:1]: Please move this blurb to `library`.

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by AZero13** [comment]
Any update on this?

**Comment by weixlu** [comment]
Hi everyone,

I ran into a compile error near the changes in this PR. 
```
./Modules/_decimal/_decimal.c:6996:12: error: too few arguments to function '_decimal_Context__apply'
 6996 |     return _decimal_Context__apply(context, x);
      |            ^~~~~~~~~~~~~~~~~~~~~~~
```
I think the issue goes beyond a typo: the wrapper is calling the wrong function. It should call `_decimal_Context__apply_impl(context, cls, x)` instead of `_decimal_Context__apply(context, x)`.

After making that change, I was able to build successfully and run the decimal tests.

@skirpichev @serhiy-storchaka Would this fix be acceptable? If so, I’m happy to open a PR.

Thanks!

update: I have opened a PR #152871, please have a look, thanks
