### PR TITLE
gh-106193: Rename and fix duplicated tests in `test_monitoring`

### LINKED ISSUE #106193: `test_monitoring` has duplicated tests
Based on https://github.com/python/core-workflow/issues/505 by @hugovk 

```
Lib/test/test_monitoring.py:973:5: F811 redefinition of unused 'test_line_then_instruction' from line 950
Lib/test/test_monitoring.py:978:5: F811 redefinition of unused 'test_instruction_then_line' from line 955
```

Before rename: `Ran 49 tests in 0.014s`
After rename:

```
======================================================================
ERROR: test_instruction_then_line (test.test_monitoring.TestInstallIncrementallly.test_instruction_then_line)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_monitoring.py", line 956, in test_instruction_then_line
    recorders = [ InstructionRecorder, LineRecorderLowNoise ]
                                       ^^^^^^^^^^^^^^^^^^^^
NameError: name 'LineRecorderLowNoise' is not defined

======================================================================
ERROR: test_line_then_instruction (test.test_monitoring.TestInstallIncrementallly.test_line_then_instruction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_monitoring.py", line 953, in test_line_then_instruction
    recorders = recorders, must_include = self.EXPECTED_LI)
                                          ^^^^^^^^^^^^^^^^
AttributeError: 'TestInstallIncrementallly' object has no attribute 'EXPECTED_LI'

----------------------------------------------------------------------
Ran 51 tests in 0.045s

FAILED (errors=2)
test test_monitoring failed
test_monitoring failed (2 errors)

== Tests result: FAILURE ==

1 test failed:
    test_monitoring

Total duration: 94 ms
Tests result: FAILURE
```

Based on the missing runtime parts in these tests, we can just remove the first two ones, I guess.

Both of these tests were introduced in https://github.com/python/cpython/commit/411b1692811b2ecac59cb0df0f920861c7cf179a by @markshannon 

### Linked PRs
* gh-109139
* gh-110897

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/python/cpython/issues/106193.
Found via https://github.com/python/core-workflow/issues/505#issuecomment-1609495331.

Fixes some copy/paste errors, and then fix some undefined names, because the redefined method name masked the unknown variables. We can work out what they should be.

# Before

We can see two pairs of tests:

```python
    @staticmethod
    def func1():
        line1 = 1

    MUST_INCLUDE_LI = [
            ('instruction', 'func1', 2),
            ('line', 'func1', 1),
            ('instruction', 'func1', 4),
            ('instruction', 'func1', 6)]

    def test_line_then_instruction(self):
        recorders = [ LineRecorder, InstructionRecorder ]
        self.check_events(self.func1,
                          recorders = recorders, must_include = self.EXPECTED_LI)

    def test_instruction_then_line(self):
        recorders = [ InstructionRecorder, LineRecorderLowNoise ]
        self.check_events(self.func1,
                          recorders = recorders, must_include = self.EXPECTED_LI)
```
```python
    @staticmethod
    def func2():
        len(())

    MUST_INCLUDE_CI = [
            ('instruction', 'func2', 2),
            ('call', 'func2', sys.monitoring.MISSING),
            ('call', 'len', ()),
            ('instruction', 'func2', 12),
            ('instruction', 'func2', 14)]



    def test_line_then_instruction(self):
        recorders = [ CallRecorder, InstructionRecorder ]
        self.check_events(self.func2,
                          recorders = recorders, must_include = self.MUST_INCLUDE_CI)

    def test_instruction_then_line(self):
        recorders = [ InstructionRecorder, CallRecorder ]
        self.check_events(self.func2,
                          recorders = recorders, must_include = self.MUST_INCLUDE_CI)
```

# After

Fixes: 

* Test names are based on the `recorders`.
* `self.EXPECTED_LI` should be `self.MUST_INCLUDE_CI`, like the others.
* `LineRecorderLowNoise` should be `LineRecorder`, like the previous test.
* `('line', 'func1', 1)` needed changing to `('line', 'func1', 2)` to pass.

```python
    @staticmethod
    def func1():
        line1 = 1

    MUST_INCLUDE_LI = [
            ('instruction', 'func1', 2),
            ('line', 'func1', 2),
            ('instruction', 'func1', 4),
            ('instruction', 'func1', 6)]

    def test_line_then_instruction(self):
        recorders = [ LineRecorder, InstructionRecorder ]
        self.check_events(self.func1,
                          recorders = recorders, must_include = self.MUST_INCLUDE_LI)

    def test_instruction_then_line(self):
        recorders = [ InstructionRecorder, LineRecorder ]
        self.check_events(self.func1,
                          recorders = recorders, must_include = self.MUST_INCLUDE_LI)

```
```python
    @staticmethod
    def func2():
        len(())

    MUST_INCLUDE_CI = [
            ('instruction', 'func2', 2),
            ('call', 'func2', sys.monitoring.MISSING),
            ('call', 'len', ()),
            ('instruction', 'func2', 12),
            ('instruction', 'func2', 14)]



    def test_call_then_instruction(self):
        recorders = [ CallRecorder, InstructionRecorder ]
        self.check_events(self.func2,
                          recorders = recorders, must_include = self.MUST_INCLUDE_CI)

    def test_instruction_then_call(self):
        recorders = [ InstructionRecorder, CallRecorder ]
        self.check_events(self.func2,
                          recorders = recorders, must_include = self.MUST_INCLUDE_CI)
```

cc @markshannon @sobolevn 

* Issue: gh-106193

### CODE REVIEW

**Comment by hugovk** [comment]
(Resolved conflict.)

**Comment by markshannon** [comment]
Thanks
