### ISSUE TITLE
...colorama import just_fix_windows_console NOT working on Ubuntu 20.04

### ISSUE THREAD

**Issue by klausbu** [python/cpython#115954]
# Bug report

### Bug description:

**I want to use a python3 application called PlanformCreator2 but I keep getting the following error related to colorama and just_fix_windows_console() :**

Traceback (most recent call last):
  File "/home/klaus/Programme/PlanformCreator2SC/AirfoilEditor.py", line 39, in <module>
    from common_utils       import * 
  File "/home/klaus/Programme/PlanformCreator2SC/modules/common_utils.py", line 9, in <module>
    from colorama import just_fix_windows_console
**ImportError: cannot import name 'just_fix_windows_console' from 'colorama' (/usr/lib/python3/dist-packages/colorama/__init__.py)**

This issue comes up in blogs from 2022 when downgrading colorama to colorama==0.4.4 and bayesian_optimization to bayesian_optimization==1.4.1 seems to have fixed the problem. This is not the case anymore, at least not under Ubuntu 20.04.

Can I fix the problem or is it a real bug?

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
Hello!
This repository is intended as CPython bug tracker. It looks like your problem isn't related to CPython.
Here's colorama repository: https://github.com/tartley/colorama
