### PR TITLE
gh-114917: add support for AI_NUMERICSERV in getaddrinfo emulation

### PR DESCRIPTION
**Pull request by maxbachmann**
* Issue: gh-114917

### CODE REVIEW

**Review by rruuaanng — APPROVED** [review]
LGTM

**Review by vstinner — COMMENTED** [review]
Can you write a test for this feature?

**Comment by maxbachmann** [comment]
I am not sure which currently tested target even runs this code. This is only included conditionally via:
```
#if !defined(HAVE_GETNAMEINFO)
#define getnameinfo fake_getnameinfo
#include "getnameinfo.c"
#endif // HAVE_GETNAMEINFO
```

There is already the following test:
```
        # Issue 17269: test workaround for OS X platform bug segfault
        if hasattr(socket, 'AI_NUMERICSERV'):
            try:
                # The arguments here are undefined and the call may succeed
                # or fail.  All we care here is that it doesn't segfault.
                socket.getaddrinfo("localhost", None, 0, 0, 0,
                                   socket.AI_NUMERICSERV)
            except socket.gaierror:
                pass
```
we probably don't require this to be conditional any more.

**Comment by maxbachmann** [comment]
I could add something like
```
self.assertRaises(socket.gaierror, socket.getaddrinfo, "localhost", "http", flags=socket.AI_NUMERICSERV)
```
but this wouldn't really test the fallback unless we have a tested target that uses it (we use the fallback on the playstation)

File: Modules/getaddrinfo.c [hunk 1]
```diff
@@ -351,6 +351,9 @@ getaddrinfo(const char*hostname, const char*servname,
             struct servent *sp;
             const char *proto;
 
+            if (ai->ai_flags & AI_NUMERICSERV)
```
Comment (vstinner) [inline Modules/getaddrinfo.c]: PEP 7: Please add { ... } braces around the return for new code like this one.

**Review by vstinner — APPROVED** [review]
LGTM. I just have a minor coding style request.

File: Modules/getaddrinfo.c (hunk 1 above)
Comment (maxbachmann) [reply Modules/getaddrinfo.c]: Added the braces. I also noticed, that this should have used `ERR(EAI_NONAME);` instead of `return EAI_NONAME;` to set the res to NULL similar to the other error conditions.

**Comment by vstinner** [comment]
> @vstinner is there still something stopping this from getting merged?

I don't know Modules/getaddrinfo.c. Which platforms are using it? It looks like dead code to me. It starts with a big `#if 0` and then most code is disabled unless the `HAVE_NETDB_H` macro is defined.

My `pyconfig.h` has:

```
/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1
```

but `Modules/getaddrinfo.c` doesn't include `pyconfig.h` nor `Python.h`.

**Comment by vstinner** [comment]
I tried to using this Linux with the patch:

```diff
diff --git a/Modules/socketmodule.c b/Modules/socketmodule.c
index 916ad35623e..c49d0d53042 100644
--- a/Modules/socketmodule.c
+++ b/Modules/socketmodule.c
@@ -448,6 +448,8 @@ remove_unusable_flags(PyObject *m)
 
 #endif
 
+#undef HAVE_GETADDRINFO
+
 /* I know this is a bad practice, but it is the easiest... */
 #if !defined(HAVE_GETADDRINFO)
 /* avoid clashes with the C library definition of the symbol. */
```

On Linux, I get many build errors:

```
./Modules/getaddrinfo.c:206:30: error: 'EAI_MAX' undeclared (first use in this function); did you mean 'AF_MAX'?
./Modules/getaddrinfo.c:285:17: error: 'EAI_BADHINTS' undeclared (first use in this function); did you mean 'EAI_BADFLAGS'?
./Modules/getaddrinfo.c:286:32: error: 'AI_MASK' undeclared (first use in this function)
./Modules/getaddrinfo.c:354:19: error: invalid type argument of '->' (have 'struct addrinfo')
./Modules/getaddrinfo.c:384:25: error: 'EAI_PROTOCOL' undeclared (first use in this function); did you mean 'SO_PROTOCOL'?
./Modules/getaddrinfo.c:512:10: error: implicit declaration of function 'getipnodebyaddr'; did you mean 'getnetbyaddr'? [-Wimplicit-function-declaration]
./Modules/getaddrinfo.c:512:8: error: assignment to 'struct hostent *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
./Modules/getaddrinfo.c:561:14: error: implicit declaration of function 'getipnodebyname'; did you mean 'getprotobyname'? [-Wimplicit-function-declaration]
./Modules/getaddrinfo.c:561:12: error: assignment to 'struct hostent *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
./Modules/getaddrinfo.c:564:12: error: assignment to 'struct hostent *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
```

How did you test your change? Are using using macOS?

**Comment by maxbachmann** [comment]
> I don't know Modules/getaddrinfo.c. Which platforms are using it? It looks like dead code to me. It starts with a big #if 0 and then most code is disabled unless the HAVE_NETDB_H macro is defined.

It's only used when `HAVE_GETADDRINFO` isn't defined. In this case it's directly including the c file and so doesn't need the imports.

> On Linux, I get many build errors:

 I assume you didn't undef this for enough code. The include of  `addrinfo.h` in line 423 would need this define to already be removed.

> How did you test your change? Are using using macOS?

We are using it in our playstation port of CPython

**Comment by vstinner** [comment]
> We are using it in our playstation port of CPython

Oh ok. A few lines to support PlayStation sounds reasonable, I merged your PR. Thanks.
