### PR TITLE
gh-123242: Note that type.__annotations__ may not exist

### LINKED ISSUE #123242: ModuleType.__annotations__ and type.__annotations__ result in AttributeError
# Bug report

### Bug description:

If you call dir() on ModuleType or type, it shows `__annotations__` as one of the attributes. However, when you attempt to access that attribute, for ModuleType you get `AttributeError: type object 'module' has no attribute '__annotations__'` and for type you get `AttributeError: type object 'type' has no attribute '__annotations__'`.

```python
>>> from types import ModuleType
>>> dir(ModuleType)
['__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
>>> ModuleType.__annotations__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'module' has no attribute '__annotations__'
>>> 
>>> dir(type)
['__abstractmethods__', '__annotations__', '__base__', '__bases__', '__basicsize__', '__call__', '__class__', '__delattr__', '__dict__', '__dictoffset__', '__dir__', '__doc__', '__eq__', '__flags__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__instancecheck__', '__itemsize__', '__le__', '__lt__', '__module__', '__mro__', '__name__', '__ne__', '__new__', '__or__', '__prepare__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__setattr__', '__sizeof__', '__str__', '__subclasscheck__', '__subclasses__', '__subclasshook__', '__text_signature__', '__weakrefoffset__', 'mro']
>>> type.__annotations__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'type' has no attribute '__annotations__'
```

I found this bug because I have a method that iterates over the attributes returned from dir and gets each attribute.  After upgrading from Python 3.8 to 3.11, this caused an interesting failure.  I would expect that attributes returned by dir() would be accessible and not result in an AttributeError.

### CPython versions tested on:

3.11, 3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-124557
* gh-124562
* gh-124569

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Closes #123242. The real criterion is that the attribute does not
exist on heap types, but I don't think we should discuss heap vs.
static types in the language reference.

* Issue: gh-123242

----
📚 Documentation preview 📚: https://cpython-previews--124557.org.readthedocs.build/

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]

**Review by picnixz — APPROVED** [review]
> The real criterion is that the attribute does not
exist on heap types, but I don't think we should discuss heap vs.
static types in the language reference.

I concur.
