### PR TITLE
gh-102871: Remove obsolete browsers from webbrowser

### PR DESCRIPTION
**Pull request by DBJim**
#102871

### CODE REVIEW

**Comment by terryjreedy** [comment]
Do any of these removals need deprecation?

**Review by sobolevn — COMMENTED** [review]
This is literally the first time I hear about most of them.
Even https://browsersl.ist/ and https://caniuse.com/ do not list them anywhere.

I don't think that using Python3.12 and Netscape at the same time is even possible in this reality :)

File: Misc/NEWS.d/next/Library/2023-03-21-15-17-07.gh-issue-102871.U9mchn.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Remove support for obsolete browsers from :mod:`webbrowser`
```
Comment (eendebakpt) [inline Misc/NEWS.d/next/Library/2023-03-21-15-17-07.gh-issue-102871.U9mchn.rst]:
```suggestion
Remove support for obsolete browsers from :mod:`webbrowser` and add support for the Epiphany (GNOME Web) browser.
```

Comment (DBJim) [reply Misc/NEWS.d/next/Library/2023-03-21-15-17-07.gh-issue-102871.U9mchn.rst]: Thanks for the review! I only renamed the class without adding support. Previously, it supported 'Galeon' and 'Epiphany' on Gnome. Galeon is no longer used.

File: Lib/webbrowser.py [hunk 2]
```diff
@@ -475,35 +425,25 @@ def register_X_browsers():
     if "KDE_FULL_SESSION" in os.environ and shutil.which("kfmclient"):
         register("kfmclient", Konqueror, Konqueror("kfmclient"))
 
+    # Common symbolic link for the default X11 browser
     if shutil.which("x-www-browser"):
         register("x-www-browser", None, BackgroundBrowser("x-www-browser"))
```
Comment (merwok) [inline Lib/webbrowser.py:431]: There is also `sensible-browser` in Debian and derived operating systems!

(Both these mecanism are more or less replaced by xdg-open these days.
This is just a note, let’s keep x-www-browser and not add sensible-browser.)

Comment (DBJim) [reply Lib/webbrowser.py:431]: Good spot!

I came across this issue - unsure if this could be a fix? https://github.com/python/cpython/issues/101893

I saw your edit :) but is it worth adding sensible-browser for good measure? What are your thoughts?

Comment (merwok) [reply Lib/webbrowser.py:431]: See my message: no need to add sensible-browser at this point.

**Comment by merwok** [comment]
I propose to merge this for 3.12 without a note in what’s new and module docs, no deprecation warning, and no backports.

**Comment by terryjreedy** [comment]
The test failure is a patchcheck whitespace failure in webbrowser.py.  James, please run patchcheck in your local repository with the branch checked out.  Either `make patchcheck` or `python tools/scripts/patchcheck.py` on windows.  If something is changed, which there should be, commit and push as usual.

File: Lib/webbrowser.py [hunk 3]
```diff
@@ -401,45 +390,6 @@ def open(self, url, new=0, autoraise=True):
...
-
-    def _remote(self, action):
-        s = self._find_grail_rc()
-        if not s:
-            return 0
-        s.send(action)
-        s.close()
-        return 1
-
     def open(self, url, new=0, autoraise=True):
```
Comment (merwok) [inline Lib/webbrowser.py:394]: Let’s keep two empty lines between top-level classes and function

```suggestion

    def open(self, url, new=0, autoraise=True):
```

Comment (DBJim) [reply Lib/webbrowser.py:394]: Thanks, I've applied your suggestion and made Terry's requested fix in a new commit

**Review by merwok — CHANGES_REQUESTED** [review]
Name the removed browsers in the news note, and in a versionchanged note in the module docs.

**Comment by DBJim** [comment]
I have made the requested changes; please review again.

**Comment by merwok** [comment]
I don’t get the note about Firefox older than version 35, can you explain?

**Comment by DBJim** [comment]
> I don’t get the note about Firefox older than version 35, can you explain?

Sure! 'Netscape' class used to be used as an alias for Firefox until 2015. The current Firefox handling was added to webbrowser in 2015 because support for the -raise, -remote and other arguments used by the old 'Netscape' class was dropped in Firefox v36+. The discussion is here: https://bugs.python.org/issue23262

There was discussion to drop support for the old class 'Netscape' in that issue, but it was decided to keep for backwards compatibility with old browsers which may have still had a user base then. Since it's been another 7 years since that discussion, I suggest the class is not required in future versions of Python.

**Review by merwok — APPROVED** [review]

File: Lib/webbrowser.py [hunk 4]
```diff
@@ -570,14 +504,15 @@ def register_standard_browsers():
 
         # Also try console browsers
         if os.environ.get("TERM"):
+            # Common symbolic link for the default text-based browser
             if shutil.which("www-browser"):
                 register("www-browser", None, GenericBrowser("www-browser"))
-            # The Links/elinks browsers <http://artax.karlin.mff.cuni.cz/~mikulas/links/>
+            # The Links/elinks browsers <http://links.twibright.com//>
```
Comment (serhiy-storchaka) [inline Lib/webbrowser.py]:
```suggestion
            # The Links/elinks browsers <http://links.twibright.com/>
```

**Review by serhiy-storchaka — COMMENTED** [review]
LGTM.

It may be worth to add also a What's New entry (in the "Removed" section).

**Review by serhiy-storchaka — APPROVED** [review]

**Comment by vstinner** [comment]
This issue broke the Konqueror class which still uses the _remote() method, removed by this PR:

```
$ ./python -m webbrowser https://www.google.com/
Traceback (most recent call last):
  File "/home/vstinner/python/main/Lib/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vstinner/python/main/Lib/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/vstinner/python/main/Lib/webbrowser.py", line 631, in <module>
    main()
  File "/home/vstinner/python/main/Lib/webbrowser.py", line 626, in main
    open(url, new_win)
  File "/home/vstinner/python/main/Lib/webbrowser.py", line 86, in open
    if browser.open(url, new, autoraise):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vstinner/python/main/Lib/webbrowser.py", line 398, in open
    ok = self._remote("LOAD " + url)
         ^^^^^^^^^^^^
AttributeError: 'Konqueror' object has no attribute '_remote'
```

By the way, webbrowser.Konqueror defines twice its ``open()`` method!

**Comment by sobolevn** [comment]
@vstinner seems like a bad merge conflict resolution, PR is here: https://github.com/python/cpython/issues/105745
