### ISSUE TITLE
Different output from importlib.resources.files() in REPL in 3.12 versus 3.13

### ISSUE THREAD

**Issue by danielhollas** [python/cpython#121190]
# Bug report

### Bug description:

Running `importlib.resources.files()` without specifying the anchor parameter in interactive REPL in Python 3.12 raises a rather unhelpful error:

```python
>>> import importlib.resources
>>> importlib.resources.files()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.12/importlib/resources/_common.py", line 45, in wrapper
    return func()
           ^^^^^^
  File "/usr/lib64/python3.12/importlib/resources/_common.py", line 56, in files
    return from_package(resolve(anchor))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/resources/_common.py", line 113, in from_package
    reader = spec.loader.get_resource_reader(spec.name)
                                             ^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/resources/_adapters.py", line 17, in __getattr__
    return getattr(self.spec, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
```

It would be nice to return something more helpful. The documentation doesn't mention that this function can raise, so I am assuming that raising AttributeError is not part of the public API?

However, on a locally built Python from current main branch, this call returns a path to `Lib/_pyrepl`. Even more surprising though is that this also happens when running the OLD REPL with `TERM=dumb ./python`

```python
❯ TERM=dumb ./python 
Python 3.14.0a0 (heads/main:1a84bdc237, Jun 30 2024, 21:44:46) [GCC 13.3.1 20240522 (Red Hat 13.3.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
warning: can't use pyrepl: terminal doesn't have the required clear capability
>>> import importlib.resources
>>> importlib.resources.files()
PosixPath('/home/hollas/software/cpython/Lib/_pyrepl')
```

### CPython versions tested on:

3.12, CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-138531
* gh-148460

**Comment by lysnikolaou** [comment]
> Even more surprising though is that this also happens when running the OLD REPL with `TERM=dumb ./python`

`TERM=dumb` does not enable the old REPL. The env var is called `PYTHON_BASIC_REPL`.

**Comment by danielhollas** [comment]
> TERM=dumb does not enable the old REPL. The env var is called PYTHON_BASIC_REPL.

Well, while it may not enable it explicitly, implicitly it does since pyrepl will not start with this type of terminal.

```python
❯ TERM=DUMB ./python 
Python 3.14.0a0 (heads/main:1a84bdc237, Jun 30 2024, 21:44:46) [GCC 13.3.1 20240522 (Red Hat 13.3.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
warning: can't use pyrepl: setupterm: could not find terminal
>>> import importlib.resources
>>> importlib.resources.files()
PosixPath('/home/hollas/software/cpython/Lib/_pyrepl')
```

But you are right that actually using `PYTHON_BASIC_REPL` will actually run the old REPL directly, and will produce the same behaviour as in 3.12

```
❯ PYTHON_BASIC_REPL=1 ./python 
Python 3.14.0a0 (heads/main:1a84bdc237, Jun 30 2024, 21:44:46) [GCC 13.3.1 20240522 (Red Hat 13.3.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib.resources
>>> importlib.resources.files()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    importlib.resources.files()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/hollas/software/cpython/Lib/importlib/resources/_common.py", line 45, in wrapper
    return func()
  File "/home/hollas/software/cpython/Lib/importlib/resources/_common.py", line 56, in files
    return from_package(resolve(anchor))
  File "/home/hollas/software/cpython/Lib/importlib/resources/_common.py", line 116, in from_package
    reader = spec.loader.get_resource_reader(spec.name)
                                             ^^^^^^^^^
  File "/home/hollas/software/cpython/Lib/importlib/resources/_adapters.py", line 17, in __getattr__
    return getattr(self.spec, name)
AttributeError: 'NoneType' object has no attribute 'name'
>>>
```

Note that I am not saying that the pyrepl behaviour is wrong here, just noting the difference. If anything, I'd change the behaviour in the old REPL so that at least it fails a bit more gracefully (not an obscure AttributeError).

**Comment by whitphx** [comment]
#134275 should fix the new REPL's different behavior than the old one,
while the issue below still is there
> It would be nice to return something more helpful. The documentation doesn't mention that this function can raise, so I am assuming that raising AttributeError is not part of the public API?

**Comment by whitphx** [comment]
Hi from PyConTW sprint.

`SpecLoaderAdapter` accesses `spec`'s attributes such as `spec.name`
https://github.com/python/cpython/blob/fc0305a2d8bef7cffaa4137bb4937bd5a16a7a38/Lib/importlib/resources/_adapters.py#L17
while `spec` can be `None` when the `package` is `__main__` as [documented](https://docs.python.org/3/reference/import.html#main-spec).
https://github.com/python/cpython/blob/fc0305a2d8bef7cffaa4137bb4937bd5a16a7a38/Lib/importlib/resources/_adapters.py#L168

`importlib.resources._common.from_package(package)` needs to take care of the case where `package.__spec__` is `None`.

Let me take a closer look...

---

- Code around it was introduced in https://github.com/python/cpython/pull/24670
- Looks like the PR intended to make `importlib.resources` synched with https://github.com/python/importlib_resources, and `importlib_resources` also has the same problem as this issue.
```
>>> import importlib_resources
>>> importlib_resources.files()
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    importlib_resources.files()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/workspace/cpython/.venv/lib/python3.15/site-packages/importlib_resources/_common.py", line 45, in wrapper
    return func()
  File "/workspace/cpython/.venv/lib/python3.15/site-packages/importlib_resources/_common.py", line 56, in files
    return from_package(resolve(anchor))
  File "/workspace/cpython/.venv/lib/python3.15/site-packages/importlib_resources/_common.py", line 117, in from_package
    reader = spec.loader.get_resource_reader(spec.name)
                                             ^^^^^^^^^
  File "/workspace/cpython/.venv/lib/python3.15/site-packages/importlib_resources/_adapters.py", line 17, in __getattr__
    return getattr(self.spec, name)
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by jaraco** [comment]
This change should be included in Python 3.15. Thanks for the patience awaiting merge.
