### PR TITLE
gh-130164: Fix inspect.Signature.bind() handling of positional-only args without defaults

### LINKED ISSUE #130164: Signature.bind allows certain positional-only parameters as keywords
# Bug report

### Bug description:

Prior to 3.13, the following code correctly raised a `TypeError` (I've tested 3.8-3.12, but see the last paragraph below):
```python
def fun(x, /, **kwargs):
    pass

import inspect
sig = inspect.signature(fun)
sig.bind(x=1)
```
In 3.13, the binding succeeds even though the positional-only parameter was passed as a keyword argument (of course, `fun(x=1)` fails with a `TypeError`).

As far as I can tell this bug hasn't been previously reported, although issue #107831 reports `inspect.getcallargs` as having the same problem (prior to 3.13, unlike this bug).

I'm guessing the bug was introduced by #103404. If I try a version of 3.12 containing that patch (rather than the older versions I had installed previously), e.g. 3.12.9, it also exhibits the bug. It's possible that fixing the case where the positional-only parameter has a default value accidentally broke this case. Mentioning @jacobtylerwalls as the author of that PR in case they would like to take a look. Thanks!

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

### Linked PRs
* gh-130192
* gh-130271
* gh-132259

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
**Before**
`inspect.Signature.bind()` failed to raise TypeError for positional-only arguments passed by keyword (due to a regression handling the case where a default is defined).
**After**
This is fixed.

Regression in 9c15202.

Interestingly, we did have a test case for this, but it unexpectedly passed because after calling `bind()`, the test helper also calls the underlying function, making `assertRaises(TypeError, ...` succeed regardless of the behavior of `bind()`.

Closes #130164

* Issue: gh-130164

### CODE REVIEW

File: Lib/test/test_inspect/test_inspect.py [hunk 1]
```diff
@@ -5349,7 +5353,7 @@ def test(a_po, b_po, c_po=3, /, foo=42, *, bar=50, **kwargs):
         self.assertEqual(self.call(test, 1, 2, c_po=4),
                          (1, 2, 3, 42, 50, {'c_po': 4}))
 
-        with self.assertRaisesRegex(TypeError, "missing 2 required positional arguments"):
+        with self.assertRaisesRegex(TypeError, "missing a required positional-only argument: 'a_po'"):
```
Comment (jacobtylerwalls) [inline Lib/test/test_inspect/test_inspect.py:5356]: Some of these cases could be moved to the existing method `test_signature_bind_posonly_kwargs()` if desired?

**Review by dfremont — APPROVED** [review]
Thanks for the very quick fix, @jacobtylerwalls! The new logic looks correct to me and does fix the bug I reported (the exception message is slightly different than a direct call to the function, but I at least don't care about that).

**Comment by skirpichev** [comment]
CC @picnixz

**Review by skirpichev — APPROVED** [review]

**Comment by jacobtylerwalls** [comment]
Thanks for the review (and the original report!)

> (the exception message is slightly different than a direct call to the function, but I at least don't care about that).

Right, this was something I was trying to keep to in the original PR (#103404), but during review discussion there I became convinced it was of only marginal benefit. (This time around it seemed too complicated to be worth it, on first look anyway.)

**Review by serhiy-storchaka — APPROVED** [review]
LGTM. :+1:
