### PR TITLE
gh-144490: Fix mimalloc debug build

### PR DESCRIPTION
**Pull request by yoney**
Fix mimalloc C++ compilation error in debug builds.

The `_mi_assert_fail` declaration uses `mi_decl_throw`, which expands to `__THROW` (for `__GNUC__ `). In C, `__THROW` is `__attribute__((__nothrow__))` and works anywhere. In C++, `__THROW` is `noexcept(true)`, which must come after the parameter list.

  Before:
```
  // C:   __attribute__((__nothrow__)) void _mi_assert_fail(...);
  // C++: noexcept(true) void _mi_assert_fail(...);  <- Error, noexcept(...) must be after the params
```

After:
```
  // C:   void _mi_assert_fail(...) __attribute__((__nothrow__));
  // C++: void _mi_assert_fail(...) noexcept(true);
```

This fix also allows removing the `Py_DEBUG` guard in `test_cppext/extension.cpp`, so internal C API headers are now tested in debug builds too.

It’s possible this issue was introduced in #122587, though I haven’t verified it

Test:
```
$ ./configure --with-pydebug --disable-gil
$ make
$ ./python -m test test.test_cppext -u cpu=1
```

cc: @vstinner @colesbury @DinoV 

* Issue: gh-144490

### CODE REVIEW

**Review by vstinner — APPROVED** [review]
LGTM. I confirm that `test_cppext.TestInteralCAPI` pass on Linux with Python built in debug mode.
