### ISSUE TITLE
Debian buster's python 3.7.3 release has "ImportError: cannot import name 'Literal' from 'typing'"

### ISSUE THREAD

**Issue by DXXS** [python/cpython#95988]
File "/usr/local/lib/python3.7/dist-packages/validate_email/dns_check.py", line 4, in <module>
    from typing import List, Literal, FrozenSet, Union, Type
ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)

**Comment by DXXS** [comment]
Tried apt install python3/buster-backports also, but apparently no upgrades yet made available...

**Comment by JelleZijlstra** [comment]
`Literal` was only added to typing in 3.8 (PEP-586). I assume Debian has a 3.8 package available, but this repo isn't responsible for Debian's packaging.

**Comment by ericvsmith** [comment]
You'll need to upgrade to python 3.8 to get `typing.Literal`. See https://docs.python.org/3/library/typing.html#typing.Literal. There is no version available for 3.7.

You could also bring this up on the validate_email tracker.

**Comment by DXXS** [comment]
Huh? I did not write this 'dns_check.py'; apparently whoever wrote it (& apparently put it in their 3.7 dist?) didn't bother to make sure that it worked in 3.7 first.

Also, Debian 10 does not appear to have any official python versions above 3.7 available in their standard repositories (or even in buster-backports), even though it's reportedly a 'LTS'/5y support version released in 2019.

**Comment by JelleZijlstra** [comment]
That's a problem for Debian to fix, not CPython. Perhaps they incorrectly provided a package for https://pypi.org/project/validate_email/ that no longer supports Python 3.7.

**Comment by DXXS** [comment]
Well, if they're claiming that it's part of 'python3.7/dist-packages', and it's not what you provide(d) with python3.7, then I think that in the commercial world, that'd be 'false advertising' or something.

**Comment by DXXS** [comment]
FWIW, At the bottom of their 'Python' page, they actually refer people to go to your site & get the source : https://wiki.debian.org/Python#Installing_from_Source

**Comment by JelleZijlstra** [comment]
dist-packages are third-party packages, not part of CPython itself.

**Comment by DXXS** [comment]
Hmm; not sure why they don't call it '3p-packages' or something instead then...
